// Technology Assessment Dashboard - Data Sources
// Multiple curated datasets from AI assistants for comparison

// COORDINATE SYSTEM FOR HYPE CYCLE:
// Innovation Trigger: x=0-20, y=80-95 (low x, high y - starting climb)
// Peak of Inflated Expectations: x=20-35, y=5-20 (peak x, low y - at top)
// Trough of Disillusionment: x=35-50, y=65-80 (mid x, high y - bottom)
// Slope of Enlightenment: x=50-75, y=40-60 (ascending x, mid y - climbing)
// Plateau of Productivity: x=75-100, y=40-55 (high x, mid-low y - stable)

// Claude.ai Generated Dataset
const technologiesClaude = [
  {
    id: 1,
    name: "Agentic AI",
    phase: "innovation",
    x: 15,
    y: 85,
    trl: 4,
    impact: 9,
    barriers: 7,
    sustainability: 4,
    strategicFit: 8,
    category: "AI & Automation",
    notes: "Autonomous AI systems with minimal oversight",
    source: "Gartner 2024, McKinsey 2025",
  },
  {
    id: 2,
    name: "Generative AI",
    phase: "trough",
    x: 42,
    y: 68,
    trl: 6,
    impact: 9,
    barriers: 5,
    sustainability: 5,
    strategicFit: 7,
    category: "AI & Automation",
    notes: "Moving past peak hype to ROI focus",
    source: "Gartner 2024",
  },
  {
    id: 3,
    name: "AI-Augmented Software Engineering",
    phase: "innovation",
    x: 12,
    y: 88,
    trl: 5,
    impact: 8,
    barriers: 4,
    sustainability: 3,
    strategicFit: 6,
    category: "Developer Tools",
    notes: "Revolutionizing developer productivity",
    source: "Gartner 2024",
  },
  {
    id: 4,
    name: "Multiagent Systems",
    phase: "innovation",
    x: 8,
    y: 82,
    trl: 3,
    impact: 9,
    barriers: 8,
    sustainability: 4,
    strategicFit: 9,
    category: "AI & Automation",
    notes: "Coordinated autonomous AI agents",
    source: "Gartner 2024",
  },
  {
    id: 5,
    name: "Humanoid Robots",
    phase: "peak",
    x: 28,
    y: 15,
    trl: 4,
    impact: 8,
    barriers: 9,
    sustainability: 6,
    strategicFit: 10,
    category: "Robotics",
    notes: "Physical AI embodiments entering workplace",
    source: "Gartner 2024, McKinsey 2025",
  },
  {
    id: 6,
    name: "Structural Battery Composites",
    phase: "slope",
    x: 62,
    y: 48,
    trl: 5,
    impact: 8,
    barriers: 6,
    sustainability: 2,
    strategicFit: 7,
    category: "Energy & Materials",
    notes: "Weight-bearing energy storage for EVs",
    source: "WEF 2025",
  },
  {
    id: 7,
    name: "Green Nitrogen Fixation",
    phase: "slope",
    x: 58,
    y: 51,
    trl: 4,
    impact: 7,
    barriers: 7,
    sustainability: 1,
    strategicFit: 5,
    category: "Climate Tech",
    notes: "Sustainable ammonia production",
    source: "WEF 2025",
  },
  {
    id: 8,
    name: "Generative Watermarking",
    phase: "innovation",
    x: 18,
    y: 90,
    trl: 5,
    impact: 7,
    barriers: 5,
    sustainability: 2,
    strategicFit: 6,
    category: "Trust & Security",
    notes: "AI content authentication",
    source: "WEF 2025",
  },
  {
    id: 9,
    name: "Engineered Living Therapeutics",
    phase: "slope",
    x: 55,
    y: 54,
    trl: 5,
    impact: 9,
    barriers: 8,
    sustainability: 4,
    strategicFit: 4,
    category: "Healthcare",
    notes: "Programmable microbes for medicine",
    source: "WEF 2025",
  },
  {
    id: 10,
    name: "Next-Gen Nuclear Energy",
    phase: "slope",
    x: 65,
    y: 46,
    trl: 6,
    impact: 9,
    barriers: 8,
    sustainability: 3,
    strategicFit: 6,
    category: "Energy & Materials",
    notes: "Small modular reactors (SMRs)",
    source: "WEF 2025",
  },
  {
    id: 11,
    name: "Osmotic Power Systems",
    phase: "innovation",
    x: 10,
    y: 84,
    trl: 3,
    impact: 6,
    barriers: 8,
    sustainability: 2,
    strategicFit: 5,
    category: "Energy & Materials",
    notes: "Salinity gradient energy",
    source: "WEF 2025",
  },
  {
    id: 12,
    name: "Application-Specific Semiconductors",
    phase: "slope",
    x: 70,
    y: 43,
    trl: 7,
    impact: 9,
    barriers: 7,
    sustainability: 5,
    strategicFit: 8,
    category: "Computing",
    notes: "Purpose-built chips for AI workloads",
    source: "McKinsey 2025",
  },
  {
    id: 13,
    name: "Spatial Computing",
    phase: "slope",
    x: 52,
    y: 56,
    trl: 6,
    impact: 7,
    barriers: 6,
    sustainability: 4,
    strategicFit: 8,
    category: "Immersive Tech",
    notes: "AR/VR for enterprise collaboration",
    source: "McKinsey 2025, Gartner 2024",
  },
  {
    id: 14,
    name: "Digital Twin of Customer",
    phase: "trough",
    x: 45,
    y: 65,
    trl: 5,
    impact: 7,
    barriers: 7,
    sustainability: 3,
    strategicFit: 7,
    category: "Experience Tech",
    notes: "Virtual customer representation",
    source: "Gartner 2024",
  },
  {
    id: 15,
    name: "Quantum Computing",
    phase: "trough",
    x: 40,
    y: 70,
    trl: 4,
    impact: 9,
    barriers: 9,
    sustainability: 6,
    strategicFit: 6,
    category: "Computing",
    notes: "Moving toward practical applications",
    source: "McKinsey 2025",
  },
  {
    id: 16,
    name: "AI Disease Management",
    phase: "slope",
    x: 60,
    y: 50,
    trl: 6,
    impact: 9,
    barriers: 6,
    sustainability: 3,
    strategicFit: 5,
    category: "Healthcare",
    notes: "Early detection and diagnosis",
    source: "CB Insights 2025",
  },
  {
    id: 17,
    name: "Liquid-Cooled Data Centers",
    phase: "slope",
    x: 68,
    y: 44,
    trl: 7,
    impact: 7,
    barriers: 5,
    sustainability: 2,
    strategicFit: 7,
    category: "Infrastructure",
    notes: "Energy-efficient computing",
    source: "CB Insights 2025",
  },
  {
    id: 18,
    name: "RNA Therapeutics",
    phase: "slope",
    x: 64,
    y: 47,
    trl: 6,
    impact: 9,
    barriers: 7,
    sustainability: 3,
    strategicFit: 4,
    category: "Healthcare",
    notes: "Next-gen mRNA treatments",
    source: "CB Insights 2025",
  },
  {
    id: 19,
    name: "Cyborg Wealth Advisors",
    phase: "innovation",
    x: 14,
    y: 86,
    trl: 5,
    impact: 6,
    barriers: 7,
    sustainability: 3,
    strategicFit: 3,
    category: "Financial Services",
    notes: "AI-powered investment management",
    source: "CB Insights 2025",
  },
  {
    id: 20,
    name: "Satellite Constellation Tech",
    phase: "plateau",
    x: 82,
    y: 50,
    trl: 8,
    impact: 8,
    barriers: 4,
    sustainability: 6,
    strategicFit: 8,
    category: "Space Tech",
    notes: "LEO commercialization",
    source: "CB Insights 2025",
  },
  {
    id: 21,
    name: "6G Networks",
    phase: "innovation",
    x: 6,
    y: 80,
    trl: 2,
    impact: 8,
    barriers: 9,
    sustainability: 5,
    strategicFit: 9,
    category: "Connectivity",
    notes: "Next-generation wireless",
    source: "Gartner 2024",
  },
  {
    id: 22,
    name: "Superapps",
    phase: "slope",
    x: 72,
    y: 42,
    trl: 7,
    impact: 7,
    barriers: 5,
    sustainability: 3,
    strategicFit: 6,
    category: "Experience Tech",
    notes: "All-in-one digital platforms",
    source: "Gartner 2024",
  },
  {
    id: 23,
    name: "GitOps",
    phase: "plateau",
    x: 88,
    y: 48,
    trl: 8,
    impact: 6,
    barriers: 3,
    sustainability: 2,
    strategicFit: 5,
    category: "Developer Tools",
    notes: "Infrastructure as code standard",
    source: "Gartner 2024",
  },
  {
    id: 24,
    name: "Machine Customers",
    phase: "innovation",
    x: 16,
    y: 89,
    trl: 3,
    impact: 7,
    barriers: 8,
    sustainability: 4,
    strategicFit: 7,
    category: "AI & Automation",
    notes: "AI agents as purchasing entities",
    source: "Gartner 2025",
  },
  {
    id: 25,
    name: "Collaborative Sensing",
    phase: "slope",
    x: 66,
    y: 45,
    trl: 6,
    impact: 7,
    barriers: 6,
    sustainability: 2,
    strategicFit: 10,
    category: "IoT & Sensors",
    notes: "Distributed sensor networks with AI",
    source: "WEF 2025",
  },
];

// ChatGPT Generated Dataset
const technologiesGPT = [
  // 🧠 AI & Automation
  {
    id: 1,
    name: "Agentic AI",
    phase: "peak",
    x: 30,
    y: 90,
    trl: 5,
    impact: 10,
    barriers: 7,
    sustainability: 5,
    strategicFit: 10,
    category: "AI & Automation",
    notes:
      "Autonomous AI systems capable of task orchestration and decision-making. Foundational for smart mobility and robotics applications.",
    source: "Gartner 2024, McKinsey 2025",
  },
  {
    id: 2,
    name: "Generative AI & Multimodal Models",
    phase: "slope",
    x: 55,
    y: 70,
    trl: 8,
    impact: 9,
    barriers: 3,
    sustainability: 4,
    strategicFit: 9,
    category: "AI & Automation",
    notes:
      "Mature generative models combining text, vision, and audio for city planning, robotics, and analytics.",
    source: "Gartner 2024, CB Insights 2025",
  },
  {
    id: 3,
    name: "AI-Augmented Software Engineering",
    phase: "slope",
    x: 58,
    y: 65,
    trl: 8,
    impact: 8,
    barriers: 3,
    sustainability: 4,
    strategicFit: 9,
    category: "Developer Tools",
    notes:
      "AI copilots and code generation improving R&D and digital twin development productivity.",
    source: "Gartner 2024",
  },
  {
    id: 4,
    name: "AI Safety & Governance Platforms",
    phase: "slope",
    x: 50,
    y: 60,
    trl: 7,
    impact: 8,
    barriers: 5,
    sustainability: 3,
    strategicFit: 10,
    category: "Trust & Security",
    notes:
      "Responsible AI, risk management, and compliance tooling supporting ethical smart city operations.",
    source: "WEF 2025, McKinsey 2025",
  },
  {
    id: 5,
    name: "Multi-Agent Systems",
    phase: "innovation",
    x: 20,
    y: 80,
    trl: 4,
    impact: 9,
    barriers: 7,
    sustainability: 5,
    strategicFit: 10,
    category: "AI & Automation",
    notes:
      "Networks of cooperative AI agents enabling distributed decision-making in mobility and robotics.",
    source: "Gartner 2025",
  },

  // 🤖 Robotics & Physical AI
  {
    id: 6,
    name: "Humanoid Robots",
    phase: "peak",
    x: 35,
    y: 85,
    trl: 6,
    impact: 9,
    barriers: 8,
    sustainability: 6,
    strategicFit: 10,
    category: "Robotics",
    notes:
      "Human-like robots transforming logistics, healthcare, and service industries in future smart cities.",
    source: "Gartner 2024",
  },
  {
    id: 7,
    name: "Swarm Robotics",
    phase: "innovation",
    x: 18,
    y: 70,
    trl: 4,
    impact: 9,
    barriers: 7,
    sustainability: 5,
    strategicFit: 10,
    category: "Robotics",
    notes:
      "Cooperative robotic systems for autonomous maintenance, agriculture, and public safety operations.",
    source: "McKinsey 2025",
  },

  // ⚙️ Computing & Infrastructure
  {
    id: 8,
    name: "Edge AI & Federated Learning",
    phase: "slope",
    x: 55,
    y: 60,
    trl: 8,
    impact: 9,
    barriers: 3,
    sustainability: 3,
    strategicFit: 10,
    category: "Computing",
    notes:
      "Decentralized AI enabling low-latency analytics in mobility and IoT ecosystems.",
    source: "Gartner 2025, CB Insights 2025",
  },
  {
    id: 9,
    name: "Quantum Computing",
    phase: "innovation",
    x: 15,
    y: 50,
    trl: 3,
    impact: 10,
    barriers: 9,
    sustainability: 5,
    strategicFit: 8,
    category: "Quantum Tech",
    notes:
      "Hybrid quantum-classical computation enabling advanced optimization for smart infrastructure.",
    source: "McKinsey 2025",
  },
  {
    id: 10,
    name: "Post-Quantum Cryptography",
    phase: "slope",
    x: 60,
    y: 65,
    trl: 6,
    impact: 9,
    barriers: 5,
    sustainability: 4,
    strategicFit: 9,
    category: "Trust & Security",
    notes: "Quantum-resilient cryptography securing mobility and IoT networks.",
    source: "WEF 2025",
  },

  // 🌍 Energy & Climate Tech
  {
    id: 11,
    name: "Structural Battery Composites",
    phase: "slope",
    x: 52,
    y: 58,
    trl: 7,
    impact: 9,
    barriers: 6,
    sustainability: 3,
    strategicFit: 8,
    category: "Energy & Materials",
    notes: "Lightweight power-storing materials for drones, robotics, and EVs.",
    source: "WEF 2025",
  },
  {
    id: 12,
    name: "Green Nitrogen Fixation",
    phase: "slope",
    x: 55,
    y: 55,
    trl: 6,
    impact: 8,
    barriers: 5,
    sustainability: 2,
    strategicFit: 9,
    category: "Climate Tech",
    notes:
      "Eco-friendly ammonia synthesis supporting sustainable urban agriculture.",
    source: "WEF 2025",
  },
  {
    id: 13,
    name: "Next-Gen Nuclear (SMRs)",
    phase: "slope",
    x: 50,
    y: 60,
    trl: 7,
    impact: 9,
    barriers: 7,
    sustainability: 3,
    strategicFit: 8,
    category: "Energy & Materials",
    notes:
      "Small modular reactors providing decentralized, safe energy for smart city grids.",
    source: "WEF 2025",
  },
  {
    id: 14,
    name: "Carbon Capture & Utilization",
    phase: "slope",
    x: 48,
    y: 58,
    trl: 8,
    impact: 9,
    barriers: 5,
    sustainability: 2,
    strategicFit: 9,
    category: "Climate Tech",
    notes:
      "Industrial carbon reduction technology enabling sustainability-driven urban innovation.",
    source: "McKinsey 2025",
  },

  // 🧬 BioTech & Health
  {
    id: 15,
    name: "Engineered Living Therapeutics",
    phase: "slope",
    x: 52,
    y: 63,
    trl: 6,
    impact: 9,
    barriers: 7,
    sustainability: 5,
    strategicFit: 7,
    category: "Healthcare",
    notes:
      "Engineered microbial therapies reshaping precision medicine and environmental bioremediation.",
    source: "WEF 2025",
  },
  {
    id: 16,
    name: "RNA & Epigenetic Therapies",
    phase: "slope",
    x: 58,
    y: 65,
    trl: 7,
    impact: 9,
    barriers: 6,
    sustainability: 5,
    strategicFit: 7,
    category: "Healthcare",
    notes:
      "Next-generation RNA therapeutics with potential cross-domain bio-digital applications.",
    source: "CB Insights 2025",
  },
  {
    id: 17,
    name: "Bio-Digital Interfaces",
    phase: "innovation",
    x: 15,
    y: 60,
    trl: 4,
    impact: 10,
    barriers: 8,
    sustainability: 5,
    strategicFit: 10,
    category: "BioTech",
    notes:
      "Brain-computer and neural interface systems connecting cognition with robotics and smart devices.",
    source: "McKinsey 2025",
  },
  {
    id: 18,
    name: "Synthetic Biology Platforms",
    phase: "slope",
    x: 50,
    y: 55,
    trl: 7,
    impact: 8,
    barriers: 5,
    sustainability: 4,
    strategicFit: 8,
    category: "Healthcare",
    notes:
      "Programmable biological systems enabling materials and healthcare innovation.",
    source: "WEF 2025",
  },

  // 🌐 Infrastructure & Connectivity
  {
    id: 19,
    name: "6G Networks",
    phase: "innovation",
    x: 12,
    y: 65,
    trl: 4,
    impact: 9,
    barriers: 8,
    sustainability: 5,
    strategicFit: 9,
    category: "Connectivity",
    notes:
      "Ultra-low latency wireless foundation for robotics and IoT ecosystems.",
    source: "Gartner 2024",
  },
  {
    id: 20,
    name: "Satellite Internet Constellations",
    phase: "plateau",
    x: 75,
    y: 70,
    trl: 8,
    impact: 8,
    barriers: 4,
    sustainability: 4,
    strategicFit: 8,
    category: "Space Tech",
    notes:
      "Low Earth orbit satellite networks delivering global IoT connectivity.",
    source: "CB Insights 2025",
  },
  {
    id: 21,
    name: "Collaborative Sensing Networks",
    phase: "slope",
    x: 58,
    y: 68,
    trl: 7,
    impact: 9,
    barriers: 4,
    sustainability: 3,
    strategicFit: 10,
    category: "IoT & Sensors",
    notes:
      "AI-enhanced sensor fusion supporting adaptive infrastructure and smart mobility systems.",
    source: "WEF 2025",
  },

  // 💼 Enterprise & Experience Tech
  {
    id: 22,
    name: "Digital Twin of the Customer",
    phase: "trough",
    x: 40,
    y: 50,
    trl: 6,
    impact: 8,
    barriers: 6,
    sustainability: 5,
    strategicFit: 8,
    category: "Experience Tech",
    notes:
      "Personalized digital avatars integrating behavioral and transaction data for urban analytics.",
    source: "Gartner 2024",
  },
  {
    id: 23,
    name: "Superapps",
    phase: "slope",
    x: 65,
    y: 72,
    trl: 9,
    impact: 8,
    barriers: 3,
    sustainability: 4,
    strategicFit: 8,
    category: "Experience Tech",
    notes:
      "Unified ecosystems combining commerce, mobility, and city services.",
    source: "Gartner 2024",
  },
  {
    id: 24,
    name: "Machine Customers",
    phase: "innovation",
    x: 20,
    y: 70,
    trl: 4,
    impact: 9,
    barriers: 7,
    sustainability: 5,
    strategicFit: 9,
    category: "AI & Automation",
    notes:
      "Autonomous digital entities performing B2B and B2C transactions in connected ecosystems.",
    source: "Gartner 2025",
  },
  {
    id: 25,
    name: "AI-Driven Cyber Defense",
    phase: "slope",
    x: 55,
    y: 65,
    trl: 8,
    impact: 9,
    barriers: 4,
    sustainability: 3,
    strategicFit: 10,
    category: "Trust & Security",
    notes:
      "Self-learning cybersecurity systems protecting AI, IoT, and robotic platforms.",
    source: "McKinsey 2025",
  },
  {
    id: 26,
    name: "Quantum-Safe Networking",
    phase: "innovation",
    x: 18,
    y: 55,
    trl: 4,
    impact: 9,
    barriers: 8,
    sustainability: 5,
    strategicFit: 9,
    category: "Quantum Tech",
    notes:
      "Quantum-secure communications protecting next-gen city and robotic systems.",
    source: "Gartner 2025",
  },
  {
    id: 27,
    name: "Decentralized Digital Identity (DID)",
    phase: "slope",
    x: 50,
    y: 63,
    trl: 7,
    impact: 9,
    barriers: 5,
    sustainability: 3,
    strategicFit: 10,
    category: "Trust & Security",
    notes:
      "Privacy-preserving identity systems foundational for secure mobility ecosystems.",
    source: "WEF 2025",
  },

  // 🌱 Sustainability & Green IT
  {
    id: 28,
    name: "Green IT & Sustainable Data Centers",
    phase: "slope",
    x: 60,
    y: 60,
    trl: 9,
    impact: 8,
    barriers: 3,
    sustainability: 2,
    strategicFit: 9,
    category: "Sustainability",
    notes:
      "Energy-optimized infrastructure minimizing data center carbon footprint.",
    source: "CB Insights 2025",
  },
  {
    id: 29,
    name: "Circular Electronics Manufacturing",
    phase: "innovation",
    x: 20,
    y: 58,
    trl: 5,
    impact: 8,
    barriers: 5,
    sustainability: 2,
    strategicFit: 9,
    category: "Sustainability",
    notes:
      "Circular production models reducing e-waste across smart city ecosystems.",
    source: "WEF 2025",
  },
  {
    id: 30,
    name: "AI for Climate Resilience",
    phase: "slope",
    x: 50,
    y: 62,
    trl: 8,
    impact: 10,
    barriers: 4,
    sustainability: 2,
    strategicFit: 10,
    category: "Climate Tech",
    notes:
      "AI-driven modeling for predicting and mitigating climate impacts on cities and mobility.",
    source: "McKinsey 2025",
  },
];

// Google Gemini Generated Dataset
const technologiesGemini = [
  {
    id: 1,
    name: "Agentic AI",
    phase: "peak",
    x: 30,
    y: 95,
    trl: 4,
    impact: 10,
    barriers: 8,
    sustainability: 9,
    category: "AI & Automation",
    notes:
      "Autonomous AI systems on the Peak of Inflated Expectations. Focus is shifting from GenAI to the complexity of Agent Governance.",
    source: "Gartner 2025",
    strategicFit: 10, // Highest competitive advantage and disruption potential.
  },
  {
    id: 2,
    name: "Generative AI",
    phase: "trough",
    x: 45,
    y: 20,
    trl: 7,
    impact: 9,
    barriers: 7,
    sustainability: 6,
    category: "AI & Automation",
    notes:
      "Has moved into the Trough of Disillusionment as organizations struggle to prove ROI beyond initial content creation use cases.",
    source: "Gartner 2025",
    strategicFit: 9, // Mandatory investment for content and process automation.
  },
  {
    id: 3,
    name: "AI-Augmented Software Engineering",
    phase: "slope",
    x: 65,
    y: 50,
    trl: 7,
    impact: 8,
    barriers: 4,
    sustainability: 5,
    category: "Developer Tools",
    notes:
      "AI copilots and autonomous testing/deployment tools are proving value and scaling adoption.",
    source: "Industry Consensus",
    strategicFit: 8, // High operational efficiency and time-to-market.
  },
  {
    id: 4,
    name: "Multiagent Systems",
    phase: "peak",
    x: 25,
    y: 90,
    trl: 4,
    impact: 8,
    barriers: 7,
    sustainability: 8,
    category: "AI & Automation",
    notes:
      "The foundational concept behind Agentic AI, sharing its high-hype, low-maturity position.",
    source: "Gartner 2025",
    strategicFit: 9, // Direct pathway to complex process automation.
  },
  {
    id: 5,
    name: "Post-Quantum Cryptography (PQC)",
    phase: "innovation",
    x: 10,
    y: 70,
    trl: 4,
    impact: 10,
    barriers: 6,
    sustainability: 2,
    category: "Security",
    notes:
      "Urgency is high due to the 'Harvest Now, Decrypt Later' risk, with material risk expected within five years.",
    source: "Bain 2025",
    strategicFit: 10, // Critical for future data security and regulatory compliance.
  },
  {
    id: 6,
    name: "Quantum Computing",
    phase: "innovation",
    x: 15,
    y: 80,
    trl: 3,
    impact: 10,
    barriers: 9,
    sustainability: 8,
    category: "Advanced Computing",
    notes:
      "The 'Year of Quantum' in 2025 emphasizes strategic planning for hybrid solutions; practical utility is 5-10 years out.",
    source: "McKinsey/Bain 2025",
    strategicFit: 9, // Long-term strategic differentiation for optimization and simulation.
  },
  {
    id: 7,
    name: "Spatial Computing",
    phase: "peak",
    x: 35,
    y: 90,
    trl: 6,
    impact: 8,
    barriers: 7,
    sustainability: 6,
    category: "Human-Machine Synergy",
    notes:
      "Driven by new hardware releases, expectations are high, but consumer adoption hurdles remain.",
    source: "Industry Consensus",
    strategicFit: 8, // High potential for customer experience, training, and remote work interfaces.
  },
  {
    id: 8,
    name: "Sustainable IT (GreenOps)",
    phase: "plateau",
    x: 90,
    y: 10,
    trl: 9,
    impact: 9,
    barriers: 3,
    sustainability: 1,
    category: "Sustainability",
    notes:
      "Practices like GreenOps and cloud optimization (serverless, containerization) are becoming standard and mandatory.",
    source: "Crayon/ITU 2025",
    strategicFit: 9, // Mandatory for ESG goals, cost reduction, and corporate reputation.
  },
  {
    id: 9,
    name: "Digital Immune Systems",
    phase: "slope",
    x: 60,
    y: 50,
    trl: 7,
    impact: 8,
    barriers: 5,
    sustainability: 3,
    category: "Security",
    notes:
      "Combining AI, observability, and resilience testing to create self-healing, fault-tolerant enterprise systems.",
    source: "Gartner 2025",
    strategicFit: 8, // Essential for operational resilience and minimizing downtime risk.
  },
  {
    id: 10,
    name: "Confidential Computing",
    phase: "slope",
    x: 70,
    y: 40,
    trl: 7,
    impact: 8,
    barriers: 4,
    sustainability: 3,
    category: "Security",
    notes:
      "Hardware-based security for data-in-use, seeing broad adoption across cloud providers for sensitive workloads.",
    source: "Industry Consensus",
    strategicFit: 8, // Key enabler for secure multi-party data collaboration.
  },
  {
    id: 11,
    name: "Cyber-Physical Systems",
    phase: "plateau",
    x: 80,
    y: 30,
    trl: 8,
    impact: 7,
    barriers: 6,
    sustainability: 4,
    category: "IoT & Industrial",
    notes:
      "Operational systems (OT) integrated with IT, driving smart factories and critical infrastructure.",
    source: "Industry Consensus",
    strategicFit: 7, // Core to Industry 4.0 and industrial efficiency.
  },
  {
    id: 12,
    name: "Verifiable Credentials (VCs)",
    phase: "slope",
    x: 75,
    y: 55,
    trl: 7,
    impact: 8,
    barriers: 5,
    sustainability: 4,
    category: "Security/Web3",
    notes:
      "Core component of Decentralized Identity, with adoption accelerating due to regulatory pushes (e.g., EU eIDAS).",
    source: "Gataca 2025",
    strategicFit: 8, // Improves compliance and streamlines customer onboarding (KYC).
  },
  {
    id: 13,
    name: "Synthetic Data",
    phase: "trough",
    x: 50,
    y: 25,
    trl: 6,
    impact: 7,
    barriers: 6,
    sustainability: 5,
    category: "Data & Analytics",
    notes:
      "Value proven for privacy and testing, but struggles with fidelity and acceptance in regulatory contexts.",
    source: "Industry Consensus",
    strategicFit: 7, // Essential for training AI models where real data is sensitive or scarce.
  },
  {
    id: 14,
    name: "Digital Humans",
    phase: "trough",
    x: 40,
    y: 30,
    trl: 5,
    impact: 6,
    barriers: 8,
    sustainability: 7,
    category: "Experience Tech",
    notes:
      "Moving out of peak hype as realism and scalability challenges become apparent.",
    source: "Industry Consensus",
    strategicFit: 6, // Niche application for customer service and brand presence.
  },
  {
    id: 15,
    name: "AI-Ready Data",
    phase: "peak",
    x: 30,
    y: 95,
    trl: 6,
    impact: 9,
    barriers: 5,
    sustainability: 6,
    category: "Data Infrastructure",
    notes:
      "At the Peak of Inflated Expectations, as organizations realize existing data is insufficient for scaled AI.",
    source: "Gartner 2025",
    strategicFit: 10, // Foundational, non-negotiable requirement for all scaled AI initiatives.
  },
  {
    id: 16,
    name: "Federated Learning",
    phase: "slope",
    x: 65,
    y: 45,
    trl: 6,
    impact: 7,
    barriers: 5,
    sustainability: 6,
    category: "AI & Automation",
    notes:
      "Scaling in use cases where privacy (e.g., healthcare, mobile) prevents centralized data pooling.",
    source: "Industry Consensus",
    strategicFit: 7, // Key for developing models on decentralized, sensitive datasets.
  },
  {
    id: 17,
    name: "Intelligent Applications",
    phase: "slope",
    x: 75,
    y: 45,
    trl: 8,
    impact: 7,
    barriers: 3,
    sustainability: 4,
    category: "Business Automation",
    notes:
      "Established applications enhanced with embedded AI/ML to automate tasks and improve user experience.",
    source: "Industry Consensus",
    strategicFit: 8, // Direct, incremental productivity and process improvement.
  },
  {
    id: 18,
    name: "Low-Earth Orbit Comms (LEO)",
    phase: "slope",
    x: 60,
    y: 50,
    trl: 7,
    impact: 8,
    barriers: 6,
    sustainability: 7,
    category: "Connectivity",
    notes:
      "Moving past peak; focus is on terrestrial integration and cost reduction, not just coverage.",
    source: "Industry Consensus",
    strategicFit: 7, // Provides essential, high-speed connectivity redundancy and global reach.
  },
  {
    id: 19,
    name: "Advanced Robotics",
    phase: "slope",
    x: 70,
    y: 45,
    trl: 7,
    impact: 8,
    barriers: 4,
    sustainability: 4,
    category: "Autonomous Systems",
    notes:
      "Advanced manipulation and mobile robotics for logistics and manufacturing are maturing rapidly.",
    source: "Industry Consensus",
    strategicFit: 8, // Critical for addressing labor shortages and automating physical supply chains.
  },
  {
    id: 20,
    name: "Commercial Space Tech",
    phase: "slope",
    x: 60,
    y: 50,
    trl: 6,
    impact: 8,
    barriers: 6,
    sustainability: 7,
    category: "Space Tech",
    notes:
      "Expansion of private capabilities for remote sensing, satellite services, and logistics.",
    source: "Industry Consensus",
    strategicFit: 7, // Provides unique, large-scale data acquisition and monitoring capabilities.
  },
  {
    id: 21,
    name: "6G Networks",
    phase: "innovation",
    x: 5,
    y: 85,
    trl: 2,
    impact: 8,
    barriers: 9,
    sustainability: 6,
    category: "Connectivity",
    notes:
      "Fundamental research phase; concepts like AI-driven infrastructure and massive connectivity are emerging.",
    source: "Industry Consensus",
    strategicFit: 6, // Long-term R&D investment; not imminent competitive factor.
  },
  {
    id: 22,
    name: "Superapps",
    phase: "slope",
    x: 70,
    y: 40,
    trl: 7,
    impact: 7,
    barriers: 5,
    sustainability: 7,
    category: "Experience Tech",
    notes:
      "Proven concept in Asia, but facing integration and regulatory hurdles in Western markets.",
    source: "Industry Consensus",
    strategicFit: 7, // Ecosystem strategy for customer lock-in and consolidation of services.
  },
  {
    id: 23,
    name: "GitOps",
    phase: "plateau",
    x: 85,
    y: 15,
    trl: 8,
    impact: 7,
    barriers: 3,
    sustainability: 4,
    category: "Developer Tools",
    notes:
      "A standard, mature practice for managing Kubernetes and cloud infrastructure via version control.",
    source: "Industry Consensus",
    strategicFit: 8, // High operational efficiency, security, and infrastructure reliability.
  },
  {
    id: 24,
    name: "Decentralized Identity (DID)",
    phase: "slope",
    x: 65,
    y: 60,
    trl: 7,
    impact: 8.5,
    barriers: 6,
    sustainability: 4,
    category: "Security/Web3",
    notes:
      "Maturing rapidly, driven by European regulations and the need for user-centric, privacy-preserving identity management.",
    source: "Gataca 2025",
    strategicFit: 8, // Improves customer trust, data control, and supports future digital ecosystems.
  },
];

// DeepSeek Generated Dataset

const technologiesDeepSeek = [
  {
    id: 1,
    name: "Agentic AI",
    phase: "innovation",
    x: 15,
    y: 85,
    trl: 4,
    impact: 9,
    barriers: 7,
    sustainability: 8,
    strategicFit: 9,
    category: "AI & Automation",
    notes: "Autonomous AI systems with minimal oversight",
    source: "Gartner 2024, McKinsey 2025",
  },
  {
    id: 2,
    name: "Generative AI for City Management",
    phase: "peak",
    x: 50,
    y: 95,
    trl: 7,
    impact: 9.5,
    barriers: 7.5,
    sustainability: 6.5,
    strategicFit: 9,
    category: "AI & Automation",
    notes:
      "For simulating urban scenarios, automating public services, and generating traffic/utility plans",
    source: "Gartner 2024, McKinsey 2024",
  },
  {
    id: 3,
    name: "AI-Augmented Robotics Programming",
    phase: "enlightenment",
    x: 65,
    y: 45,
    trl: 7,
    impact: 8.5,
    barriers: 6,
    sustainability: 2,
    strategicFit: 9.5,
    category: "AI & Automation",
    notes:
      "Drastically reduces time to program and re-task industrial and service robots",
    source: "Gartner 2024",
  },
  {
    id: 4,
    name: "Urban Digital Twins",
    phase: "innovation",
    x: 20,
    y: 80,
    trl: 6,
    impact: 9,
    barriers: 8,
    sustainability: 2.5,
    strategicFit: 10,
    category: "Smart City Infrastructure",
    notes:
      "Dynamic virtual model of a city for planning, simulation, and disaster response",
    source: "WEF 2024, McKinsey 2024",
  },
  {
    id: 5,
    name: "Swarm Robotics",
    phase: "trough",
    x: 40,
    y: 25,
    trl: 5,
    impact: 8.5,
    barriers: 8.5,
    sustainability: 3,
    strategicFit: 9,
    category: "Robotics",
    notes:
      "Coordinated fleets of drones or ground robots for logistics and surveillance",
    source: "CB Insights 2024",
  },
  {
    id: 6,
    name: "Solid-State Batteries",
    phase: "enlightenment",
    x: 70,
    y: 50,
    trl: 6,
    impact: 8,
    barriers: 7,
    sustainability: 3,
    strategicFit: 8.5,
    category: "Energy & Sustainability",
    notes: "Higher energy density and safety for EVs and grid storage",
    source: "McKinsey 2024, CB Insights 2024",
  },
  {
    id: 7,
    name: "Neuromorphic Computing",
    phase: "innovation",
    x: 10,
    y: 75,
    trl: 4,
    impact: 8.5,
    barriers: 9,
    sustainability: 2,
    strategicFit: 8,
    category: "Computing Hardware",
    notes: "Brain-like chips for ultra-efficient processing at the edge",
    source: "Gartner 2024, McKinsey 2024",
  },
  {
    id: 8,
    name: "Self-Healing Concrete",
    phase: "enlightenment",
    x: 75,
    y: 55,
    trl: 7,
    impact: 7,
    barriers: 6.5,
    sustainability: 2,
    strategicFit: 8,
    category: "Smart City Infrastructure",
    notes: "Reduces maintenance costs for urban infrastructure",
    source: "WEF 2024",
  },
  {
    id: 9,
    name: "Pervasive Ambient IoT",
    phase: "innovation",
    x: 25,
    y: 70,
    trl: 4,
    impact: 8,
    barriers: 8,
    sustainability: 4,
    strategicFit: 9.5,
    category: "IoT & Connectivity",
    notes: "Billions of tiny batteryless sensors embedded in the environment",
    source: "Gartner 2024",
  },
  {
    id: 10,
    name: "Edge AI for Computer Vision",
    phase: "enlightenment",
    x: 60,
    y: 40,
    trl: 8,
    impact: 9,
    barriers: 5.5,
    sustainability: 5.5,
    strategicFit: 9.5,
    category: "AI & Automation",
    notes: "Real-time video analytics for traffic management and public safety",
    source: "Gartner 2024, McKinsey 2024",
  },
  {
    id: 11,
    name: "Advanced EVTOL (Flying Cars)",
    phase: "peak",
    x: 45,
    y: 90,
    trl: 5,
    impact: 7.5,
    barriers: 9.5,
    sustainability: 5,
    strategicFit: 7,
    category: "Mobility & Transportation",
    notes: "Urban air mobility with high regulatory barriers",
    source: "McKinsey 2024, CB Insights 2024",
  },
  {
    id: 12,
    name: "Cognitive Autonomous Agents",
    phase: "innovation",
    x: 18,
    y: 78,
    trl: 4,
    impact: 9,
    barriers: 8.5,
    sustainability: 6.5,
    strategicFit: 8.5,
    category: "AI & Automation",
    notes:
      "AI agents that perform complex multi-step tasks across city systems",
    source: "Gartner 2024",
  },
  {
    id: 13,
    name: "Soft Robotics",
    phase: "trough",
    x: 35,
    y: 30,
    trl: 5,
    impact: 7.5,
    barriers: 7.5,
    sustainability: 2,
    strategicFit: 8.5,
    category: "Robotics",
    notes: "Robots made of compliant materials for safe human interaction",
    source: "WEF 2024",
  },
  {
    id: 14,
    name: "Spatial Computing & AR Cloud",
    phase: "trough",
    x: 38,
    y: 28,
    trl: 5,
    impact: 8,
    barriers: 7,
    sustainability: 4,
    strategicFit: 8.5,
    category: "Immersive Technologies",
    notes:
      "Persistent digital layer over the city for navigation and maintenance",
    source: "CB Insights 2024, Gartner 2024",
  },
  {
    id: 15,
    name: "Green Hydrogen",
    phase: "enlightenment",
    x: 68,
    y: 48,
    trl: 6,
    impact: 8,
    barriers: 7.5,
    sustainability: 2.5,
    strategicFit: 7.5,
    category: "Energy & Sustainability",
    notes: "Clean fuel for backup power and heavy transport in smart cities",
    source: "McKinsey 2024, WEF 2024",
  },
  {
    id: 16,
    name: "Decentralized Identity (DID)",
    phase: "innovation",
    x: 22,
    y: 72,
    trl: 5,
    impact: 7.5,
    barriers: 8,
    sustainability: 3,
    strategicFit: 8,
    category: "Security & Privacy",
    notes: "Citizen-controlled digital IDs for secure access to city services",
    source: "Gartner 2024, WEF 2024",
  },
  {
    id: 17,
    name: "5G/6G Advanced Network Slicing",
    phase: "enlightenment",
    x: 72,
    y: 52,
    trl: 7,
    impact: 8.5,
    barriers: 6,
    sustainability: 2.5,
    strategicFit: 9,
    category: "IoT & Connectivity",
    notes: "Dedicated virtual networks for critical services and robotics",
    source: "Gartner 2024",
  },
  {
    id: 18,
    name: "Bio-Inspired Sensors",
    phase: "innovation",
    x: 28,
    y: 68,
    trl: 4,
    impact: 7,
    barriers: 8.5,
    sustainability: 2,
    strategicFit: 7.5,
    category: "Sensors & Monitoring",
    notes:
      "Highly sensitive low-power sensors mimicking nature for environmental monitoring",
    source: "WEF 2024",
  },
  {
    id: 19,
    name: "Wireless Power Transfer",
    phase: "innovation",
    x: 12,
    y: 65,
    trl: 3,
    impact: 8,
    barriers: 9,
    sustainability: 3,
    strategicFit: 8.5,
    category: "Energy & Sustainability",
    notes: "Charging electric vehicles and robots dynamically without plugs",
    source: "CB Insights 2024",
  },
  {
    id: 20,
    name: "Explainable AI (XAI)",
    phase: "enlightenment",
    x: 62,
    y: 42,
    trl: 6,
    impact: 7.5,
    barriers: 6.5,
    sustainability: 2,
    strategicFit: 8,
    category: "AI & Automation",
    notes:
      "Critical for building trust in autonomous city systems and robotics",
    source: "Gartner 2024",
  },
  {
    id: 21,
    name: "Smart Waste Management Robots",
    phase: "plateau",
    x: 85,
    y: 20,
    trl: 8,
    impact: 6.5,
    barriers: 4.5,
    sustainability: 1.5,
    strategicFit: 8.5,
    category: "Robotics",
    notes: "Autonomous sorting and collection of recycling and waste",
    source: "Industry Reports 2024",
  },
  {
    id: 22,
    name: "Privacy-Enhancing Computation",
    phase: "enlightenment",
    x: 58,
    y: 38,
    trl: 6,
    impact: 7,
    barriers: 6,
    sustainability: 2,
    strategicFit: 7,
    category: "Security & Privacy",
    notes: "Allows data analysis without exposing personal data",
    source: "Gartner 2024",
  },
  {
    id: 23,
    name: "4D Printing",
    phase: "innovation",
    x: 8,
    y: 60,
    trl: 3,
    impact: 7.5,
    barriers: 9,
    sustainability: 4,
    strategicFit: 7,
    category: "Advanced Manufacturing",
    notes: "Materials that self-assemble for adaptive infrastructure",
    source: "WEF 2024, CB Insights 2024",
  },
  {
    id: 24,
    name: "AI-Driven Predictive Maintenance",
    phase: "enlightenment",
    x: 78,
    y: 58,
    trl: 7,
    impact: 8,
    barriers: 5,
    sustainability: 2,
    strategicFit: 9,
    category: "AI & Automation",
    notes: "For city infrastructure and robotic fleets to prevent failures",
    source: "McKinsey 2024",
  },
  {
    id: 25,
    name: "Autonomous Last-Mile Delivery Bots",
    phase: "trough",
    x: 42,
    y: 32,
    trl: 6,
    impact: 7,
    barriers: 6.5,
    sustainability: 3.5,
    strategicFit: 8,
    category: "Robotics",
    notes: "Sidewalk and road robots for package delivery",
    source: "CB Insights 2024",
  },
  {
    id: 26,
    name: "Carbon Capture & Utilization",
    phase: "innovation",
    x: 30,
    y: 62,
    trl: 5,
    impact: 7.5,
    barriers: 8.5,
    sustainability: 2,
    strategicFit: 6.5,
    category: "Energy & Sustainability",
    notes: "Directly addresses urban carbon emissions",
    source: "McKinsey 2024, WEF 2024",
  },
  {
    id: 27,
    name: "Haptic Feedback Interfaces",
    phase: "enlightenment",
    x: 64,
    y: 44,
    trl: 6,
    impact: 7,
    barriers: 6,
    sustainability: 2,
    strategicFit: 8,
    category: "Human-Machine Interface",
    notes: "For remote control of robots and immersive training",
    source: "Gartner 2024",
  },
  {
    id: 28,
    name: "Multi-Modal Fusion Sensing",
    phase: "enlightenment",
    x: 66,
    y: 46,
    trl: 6,
    impact: 8.5,
    barriers: 7,
    sustainability: 2,
    strategicFit: 9.5,
    category: "Sensors & Monitoring",
    notes: "Combining LiDAR, radar and camera data for robust perception",
    source: "Robotics Industry 2024",
  },
  {
    id: 29,
    name: "Cybersecurity Digital Twins",
    phase: "innovation",
    x: 24,
    y: 66,
    trl: 4,
    impact: 7.5,
    barriers: 7.5,
    sustainability: 3,
    strategicFit: 8,
    category: "Security & Privacy",
    notes: "Simulating city networks to proactively find vulnerabilities",
    source: "Gartner 2024",
  },
  {
    id: 30,
    name: "Agricultural Robotics (AgBots)",
    phase: "plateau",
    x: 88,
    y: 18,
    trl: 8,
    impact: 7,
    barriers: 5,
    sustainability: 2,
    strategicFit: 6,
    category: "Robotics",
    notes: "For urban vertical farming and local food security",
    source: "CB Insights 2024",
  },
];
// Emerging Technologies Dataset for Smart City & Robotics (2025–2035 Foresight)
// Synthesized from Gartner 2024/2025, WEF 2025, McKinsey 2025, and CB Insights 2025

const smartCityRoboticTechnologies = [
  {
    id: 1,
    name: "Edge AI & Federated Learning",
    phase: "slope",
    x: 55,
    y: 60,
    trl: 8,
    impact: 9,
    barriers: 3,
    sustainability: 3,
    strategicFit: 10,
    category: "Smart City Infrastructure",
    notes:
      "Decentralized AI enabling real-time analytics at intersections, utilities, and IoT nodes — core to smart mobility platforms.",
    source: "Gartner 2025, McKinsey 2025",
  },
  {
    id: 2,
    name: "Collaborative Sensing Networks",
    phase: "slope",
    x: 58,
    y: 68,
    trl: 7,
    impact: 8,
    barriers: 4,
    sustainability: 4,
    strategicFit: 10,
    category: "IoT & Sensing",
    notes:
      "AI-enhanced sensor fusion for adaptive infrastructure, traffic intelligence, and environmental monitoring.",
    source: "WEF 2025, CB Insights 2025",
  },
  {
    id: 3,
    name: "AI for Climate Resilience",
    phase: "slope",
    x: 50,
    y: 62,
    trl: 7,
    impact: 9,
    barriers: 4,
    sustainability: 2,
    strategicFit: 10,
    category: "Smart City Sustainability",
    notes:
      "Predictive modeling for urban resilience — flooding, heatwaves, air quality, and sustainability optimization.",
    source: "McKinsey 2025",
  },
  {
    id: 4,
    name: "Green IT & Sustainable Data Centers",
    phase: "plateau",
    x: 65,
    y: 60,
    trl: 9,
    impact: 8,
    barriers: 3,
    sustainability: 2,
    strategicFit: 9,
    category: "Smart Infrastructure",
    notes:
      "Energy-efficient cloud and edge systems reducing carbon footprint in smart city operations.",
    source: "CB Insights 2025, WEF 2025",
  },
  {
    id: 5,
    name: "Decentralized Digital Identity (DID)",
    phase: "slope",
    x: 50,
    y: 63,
    trl: 7,
    impact: 8,
    barriers: 5,
    sustainability: 4,
    strategicFit: 10,
    category: "Trust & Governance",
    notes:
      "Privacy-preserving citizen identity management for mobility and smart governance services.",
    source: "WEF 2025",
  },
  {
    id: 6,
    name: "Urban Digital Twins",
    phase: "innovation",
    x: 20,
    y: 50,
    trl: 5,
    impact: 10,
    barriers: 6,
    sustainability: 3,
    strategicFit: 10,
    category: "City Simulation",
    notes:
      "City-scale simulation integrating real-time data for predictive urban planning and resilience optimization.",
    source: "Gartner 2025, McKinsey 2025",
  },
  {
    id: 7,
    name: "6G & Quantum-Safe Networking",
    phase: "innovation",
    x: 15,
    y: 55,
    trl: 4,
    impact: 9,
    barriers: 8,
    sustainability: 5,
    strategicFit: 9,
    category: "Connectivity",
    notes:
      "Next-generation secure, ultra-low latency communications for mobility and IoT ecosystems.",
    source: "Gartner 2025",
  },
  {
    id: 8,
    name: "AI-Driven Cyber Defense",
    phase: "slope",
    x: 55,
    y: 65,
    trl: 8,
    impact: 9,
    barriers: 4,
    sustainability: 4,
    strategicFit: 10,
    category: "Trust & Security",
    notes:
      "Adaptive, self-learning cybersecurity systems protecting critical city and robotic infrastructures.",
    source: "McKinsey 2025",
  },
  {
    id: 9,
    name: "Circular Electronics & Green Manufacturing",
    phase: "innovation",
    x: 22,
    y: 58,
    trl: 5,
    impact: 8,
    barriers: 5,
    sustainability: 2,
    strategicFit: 8,
    category: "Sustainability",
    notes:
      "Eco-efficient materials reuse and supply chain sustainability for smart infrastructure and robotics.",
    source: "WEF 2025",
  },
  {
    id: 10,
    name: "AI-Powered Urban Mobility (V2X)",
    phase: "slope",
    x: 52,
    y: 64,
    trl: 7,
    impact: 10,
    barriers: 5,
    sustainability: 3,
    strategicFit: 10,
    category: "Smart Mobility",
    notes:
      "Vehicle-to-infrastructure communication and adaptive orchestration of connected transport systems.",
    source: "McKinsey 2025, Gartner 2025",
  },

  // 🤖 ROBOTICS TECHNOLOGIES
  {
    id: 11,
    name: "Humanoid Robots",
    phase: "peak",
    x: 35,
    y: 85,
    trl: 6,
    impact: 9,
    barriers: 8,
    sustainability: 5,
    strategicFit: 9,
    category: "Robotics",
    notes:
      "Versatile robots for logistics, service, and industrial applications with human-like dexterity.",
    source: "Gartner 2024, WEF 2025",
  },
  {
    id: 12,
    name: "Collaborative (Co-) Robots",
    phase: "plateau",
    x: 65,
    y: 70,
    trl: 9,
    impact: 8,
    barriers: 3,
    sustainability: 3,
    strategicFit: 10,
    category: "Industrial Robotics",
    notes:
      "Safe, human-collaborative robots improving productivity in shared workspaces and manufacturing.",
    source: "McKinsey 2025",
  },
  {
    id: 13,
    name: "AI-Augmented Robotics Control Systems",
    phase: "slope",
    x: 55,
    y: 65,
    trl: 8,
    impact: 10,
    barriers: 4,
    sustainability: 4,
    strategicFit: 10,
    category: "Robotics Control",
    notes:
      "Adaptive control using reinforcement learning for predictive and context-aware robotics.",
    source: "Gartner 2025",
  },
  {
    id: 14,
    name: "Swarm Robotics",
    phase: "innovation",
    x: 18,
    y: 70,
    trl: 4,
    impact: 9,
    barriers: 7,
    sustainability: 5,
    strategicFit: 9,
    category: "Autonomous Robotics",
    notes:
      "Distributed robotic collectives for inspection, maintenance, agriculture, and logistics.",
    source: "McKinsey 2025",
  },
  {
    id: 15,
    name: "Edge AI for Robotics",
    phase: "slope",
    x: 58,
    y: 63,
    trl: 8,
    impact: 9,
    barriers: 3,
    sustainability: 3,
    strategicFit: 10,
    category: "Robotics Infrastructure",
    notes:
      "On-device AI enabling local autonomy, low-latency perception, and resilience in robots.",
    source: "Gartner 2025, CB Insights 2025",
  },
  {
    id: 16,
    name: "Bio-Digital Interfaces (Neuro-Robotics)",
    phase: "innovation",
    x: 15,
    y: 60,
    trl: 4,
    impact: 10,
    barriers: 8,
    sustainability: 5,
    strategicFit: 10,
    category: "NeuroTech",
    notes:
      "Brain-computer interfaces merging human cognition with robotic systems for assistive and precision tasks.",
    source: "WEF 2025, McKinsey 2025",
  },
  {
    id: 17,
    name: "Self-Evolving Robotic Systems",
    phase: "innovation",
    x: 18,
    y: 65,
    trl: 3,
    impact: 9,
    barriers: 9,
    sustainability: 5,
    strategicFit: 8,
    category: "AI & Robotics",
    notes:
      "Robots that self-optimize behaviors and design through continuous learning and simulation.",
    source: "Gartner 2025",
  },
  {
    id: 18,
    name: "Soft Robotics & Morphological Computation",
    phase: "innovation",
    x: 20,
    y: 70,
    trl: 5,
    impact: 8,
    barriers: 6,
    sustainability: 4,
    strategicFit: 9,
    category: "Robotics Materials",
    notes:
      "Flexible, bio-inspired robotics ensuring safety and adaptability in complex human environments.",
    source: "WEF 2025",
  },
  {
    id: 19,
    name: "Swarm Intelligence + Multi-Agent Systems",
    phase: "innovation",
    x: 22,
    y: 75,
    trl: 5,
    impact: 10,
    barriers: 7,
    sustainability: 4,
    strategicFit: 10,
    category: "AI Robotics",
    notes:
      "Coordinated robot fleets using decentralized intelligence for scalable operations.",
    source: "McKinsey 2025, CB Insights 2025",
  },
  {
    id: 20,
    name: "Quantum-Enhanced Robotics Simulation",
    phase: "innovation",
    x: 12,
    y: 50,
    trl: 3,
    impact: 10,
    barriers: 9,
    sustainability: 6,
    strategicFit: 8,
    category: "Quantum Robotics",
    notes:
      "Quantum computing accelerating robotics simulation, optimization, and control systems.",
    source: "Gartner 2025",
  },
];

// Data source metadata
export const dataSources = {
  claude: {
    name: "Claude AI",
    description:
      "Curated from Gartner, WEF, McKinsey, and CB Insights 2024/2025 reports",
    count: technologiesClaude.length,
    focus: "Balanced coverage across all emerging tech domains",
  },
  gpt: {
    name: "ChatGPT",
    description: "Comprehensive 30-technology dataset with expanded categories",
    count: technologiesGPT.length,
    focus:
      "Quantum, Edge, Sustainability, AI Governance, and Bio-Digital Interfaces",
  },
  gemini: {
    name: "Google Gemini",
    description:
      "Industry consensus with emphasis on market maturity assessment",
    count: technologiesGemini.length,
    focus: "TRL accuracy and barrier analysis with 2025 market perspective",
  },
  deepSeek: {
    name: "Deep Seek AI",
    description:
      "Industry consensus with emphasis on market maturity assessment",
    count: technologiesDeepSeek.length,
    focus: "TRL accuracy and barrier analysis with 2025 market perspective",
  },
  smartCityRobotic: {
    name: "ChatGPT - Smart City & Robotics",
    description:
      "Emerging Technologies Dataset for Smart City & Robotics (2025–2035 Foresight)",
    count: smartCityRoboticTechnologies.length,
    focus: "Focus on smart city infrastructure and advanced robotics trends",
  },
};

// Export all datasets
export {
  technologiesClaude,
  technologiesGPT,
  technologiesGemini,
  technologiesDeepSeek,
  smartCityRoboticTechnologies,
};

// Default export
export default technologiesClaude;
