// Technology Assessment Dashboard - Data Sources
// Multiple curated datasets from AI assistants for comparison

// COORDINATE SYSTEM FOR HYPE CYCLE:
// Innovation Trigger: x=0-20, y=80-95 (low x, high y - starting climb)
// Peak of Inflated Expectations: x=20-35, y=5-20 (peak x, low y - at top)
// Trough of Disillusionment: x=35-50, y=65-80 (mid x, high y - bottom)
// Slope of Enlightenment: x=50-75, y=40-60 (ascending x, mid y - climbing)
// Plateau of Productivity: x=75-100, y=40-55 (high x, mid-low y - stable)

// Claude.ai Generated Dataset
const technologiesClaude = [
  {
    id: 1,
    name: "Agentic AI",
    phase: "Innovation Trigger",
    x: 8,
    y: 85,
    trl: 3,
    impact: 10,
    strategicFit: 9,
    barriers: 8,
    sustainability: 3,
    category: "AI & Automation",
    notes: "Autonomous AI systems capable of setting goals, planning, and taking action with minimal human oversight. Moving beyond chatbots to true agency.",
    source: "Industry analysis 2024-2025"
  },
  {
    id: 2,
    name: "Generative AI & Multimodal Models",
    phase: "Peak of Inflated Expectations",
    x: 35,
    y: 14,
    trl: 8,
    impact: 10,
    strategicFit: 9,
    barriers: 6,
    sustainability: 4,
    category: "AI & Automation",
    notes: "AI systems processing text, images, video, and audio simultaneously. Already deployed widely but expectations remain inflated.",
    source: "Gartner 2024, industry adoption data"
  },
  {
    id: 3,
    name: "AI-Augmented Software Engineering",
    phase: "Peak of Inflated Expectations",
    x: 40,
    y: 15,
    trl: 8,
    impact: 9,
    strategicFit: 8,
    barriers: 5,
    sustainability: 2,
    category: "Developer Tools",
    notes: "AI coding assistants and autonomous development tools. Rapid adoption but productivity claims being scrutinized.",
    source: "Developer surveys Q3 2024"
  },
  {
    id: 4,
    name: "AI Safety & Governance Platforms",
    phase: "Innovation Trigger",
    x: 8,
    y: 75,
    trl: 4,
    impact: 9,
    strategicFit: 7,
    barriers: 7,
    sustainability: 1,
    category: "Trust & Security",
    notes: "Tools for monitoring, auditing, and ensuring safe AI deployment. Critical but nascent infrastructure.",
    source: "AI safety research 2024"
  },
  {
    id: 5,
    name: "Multi-Agent Systems",
    phase: "Innovation Trigger",
    x: 10,
    y: 83,
    trl: 4,
    impact: 9,
    strategicFit: 9,
    barriers: 8,
    sustainability: 3,
    category: "AI & Automation",
    notes: "Multiple AI agents collaborating to solve complex problems. Early frameworks emerging but coordination remains challenging.",
    source: "Academic research 2024"
  },
  {
    id: 6,
    name: "Humanoid Robots",
    phase: "Innovation Trigger",
    x: 7,
    y: 90,
    trl: 5,
    impact: 9,
    strategicFit: 10,
    barriers: 9,
    sustainability: 5,
    category: "Robotics",
    notes: "General-purpose robots with human-like form factor. High visibility from Tesla, Figure, etc. but practical deployment years away.",
    source: "Robotics industry reports 2024"
  },
  {
    id: 7,
    name: "Swarm Robotics",
    phase: "Innovation Trigger",
    x: 10,
    y: 70,
    trl: 4,
    impact: 8,
    strategicFit: 9,
    barriers: 8,
    sustainability: 2,
    category: "Robotics",
    notes: "Coordinated groups of simple robots for agriculture, logistics, and disaster response. Promising but coordination protocols immature.",
    source: "Academic research 2023-2024"
  },
  {
    id: 8,
    name: "Edge AI & Federated Learning",
    phase: "Trough of Disillusionment",
    x: 45,
    y: 25,
    trl: 7,
    impact: 8,
    strategicFit: 9,
    barriers: 7,
    sustainability: 2,
    category: "Computing",
    notes: "Processing AI at the edge with privacy-preserving training. Initial hype fading but real use cases in IoT and mobile emerging.",
    source: "IoT analytics 2024"
  },
  {
    id: 9,
    name: "Quantum Computing",
    phase: "Trough of Disillusionment",
    x: 50,
    y: 33,
    trl: 4,
    impact: 10,
    strategicFit: 6,
    barriers: 10,
    sustainability: 4,
    category: "Quantum Tech",
    notes: "Practical quantum advantage remains elusive despite major investments. Error correction is the key bottleneck.",
    source: "Quantum computing benchmarks 2024"
  },
  {
    id: 10,
    name: "Post-Quantum Cryptography",
    phase: "Slope of Enlightenment",
    x: 65,
    y: 55,
    trl: 8,
    impact: 9,
    strategicFit: 8,
    barriers: 6,
    sustainability: 1,
    category: "Trust & Security",
    notes: "NIST standards published 2024. Organizations beginning systematic migration to quantum-resistant algorithms.",
    source: "NIST PQC standards 2024"
  },
  {
    id: 11,
    name: "Structural Battery Composites",
    phase: "Innovation Trigger",
    x: 10,
    y: 77,
    trl: 3,
    impact: 8,
    strategicFit: 7,
    barriers: 8,
    sustainability: 2,
    category: "Energy & Materials",
    notes: "Battery technology integrated into structural components for vehicles and devices. Promising for EVs but manufacturing challenges remain.",
    source: "Materials science research 2024"
  },
  {
    id: 12,
    name: "Green Nitrogen Fixation",
    phase: "Innovation Trigger",
    x: 8,
    y: 72,
    trl: 3,
    impact: 9,
    strategicFit: 5,
    barriers: 9,
    sustainability: 1,
    category: "Climate Tech",
    notes: "Electrochemical and biological alternatives to Haber-Bosch process. Could revolutionize fertilizer production with massive emissions reduction.",
    source: "Agricultural technology research 2024"
  },
  {
    id: 13,
    name: "Next-Gen Nuclear (SMRs)",
    phase: "Trough of Disillusionment",
    x: 48,
    y: 38,
    trl: 6,
    impact: 9,
    strategicFit: 7,
    barriers: 9,
    sustainability: 2,
    category: "Energy & Materials",
    notes: "Small Modular Reactors facing regulatory and cost challenges. Several projects delayed but tech giants renewing interest for data centers.",
    source: "Nuclear energy reports 2024"
  },
  {
    id: 14,
    name: "Carbon Capture & Utilization",
    phase: "Trough of Disillusionment",
    x: 52,
    y: 42,
    trl: 7,
    impact: 8,
    strategicFit: 6,
    barriers: 8,
    sustainability: 1,
    category: "Climate Tech",
    notes: "Direct air capture costs declining but still far from economic viability at scale. Utilization pathways emerging.",
    source: "Climate technology analysis 2024"
  },
  {
    id: 15,
    name: "Engineered Living Therapeutics",
    phase: "Innovation Trigger",
    x: 10,
    y: 82,
    trl: 4,
    impact: 9,
    strategicFit: 4,
    barriers: 9,
    sustainability: 3,
    category: "Healthcare",
    notes: "Programmable bacteria and cells as therapies. Early clinical trials showing promise but regulatory pathway uncertain.",
    source: "Biotech research 2024"
  },
  {
    id: 16,
    name: "RNA & Epigenetic Therapies",
    phase: "Slope of Enlightenment",
    x: 60,
    y: 58,
    trl: 8,
    impact: 10,
    strategicFit: 4,
    barriers: 7,
    sustainability: 2,
    category: "Healthcare",
    notes: "mRNA vaccines proved concept; now expanding to cancer and rare diseases. Epigenetic editing showing early promise.",
    source: "Pharmaceutical pipeline data 2024"
  },
  {
    id: 17,
    name: "Bio-Digital Interfaces",
    phase: "Innovation Trigger",
    x: 12,
    y: 85,
    trl: 5,
    impact: 9,
    strategicFit: 8,
    barriers: 9,
    sustainability: 3,
    category: "BioTech",
    notes: "Brain-computer interfaces from Neuralink, Synchron showing progress. Medical applications advancing faster than consumer.",
    source: "Neurotechnology research 2024"
  },
  {
    id: 18,
    name: "Synthetic Biology Platforms",
    phase: "Slope of Enlightenment",
    x: 58,
    y: 52,
    trl: 8,
    impact: 9,
    strategicFit: 6,
    barriers: 7,
    sustainability: 2,
    category: "Healthcare",
    notes: "CRISPR and gene synthesis tools becoming standardized. Commercial applications in materials, food, and medicine scaling.",
    source: "Synthetic biology market analysis 2024"
  },
  {
    id: 19,
    name: "6G Networks",
    phase: "Innovation Trigger",
    x: 11,
    y: 65,
    trl: 2,
    impact: 8,
    strategicFit: 9,
    barriers: 8,
    sustainability: 4,
    category: "Connectivity",
    notes: "Standards work beginning for 2030 deployment. Promises terahertz spectrum and integrated sensing but 5G still rolling out.",
    source: "Telecom standards bodies 2024"
  },
  {
    id: 20,
    name: "Satellite Internet Constellations",
    phase: "Slope of Enlightenment",
    x: 62,
    y: 58,
    trl: 9,
    impact: 8,
    strategicFit: 7,
    barriers: 6,
    sustainability: 5,
    category: "Space Tech",
    notes: "Starlink profitable, competitors launching. Coverage expanding but space debris concerns growing and economics challenging for competitors.",
    source: "Space industry analysis 2024"
  },
  {
    id: 21,
    name: "Collaborative Sensing Networks",
    phase: "Innovation Trigger",
    x: 12,
    y: 60,
    trl: 5,
    impact: 7,
    strategicFit: 10,
    barriers: 7,
    sustainability: 2,
    category: "IoT & Sensors",
    notes: "Distributed IoT sensors for environmental monitoring, traffic, infrastructure. Data integration and privacy challenges.",
    source: "IoT market research 2024"
  },
  {
    id: 22,
    name: "Digital Twin of the Customer",
    phase: "Peak of Inflated Expectations",
    x: 28,
    y: 13,
    trl: 6,
    impact: 8,
    strategicFit: 8,
    barriers: 7,
    sustainability: 3,
    category: "Experience Tech",
    notes: "AI-powered customer behavior modeling. Marketing hype strong but privacy concerns and actual predictive value being questioned.",
    source: "Marketing technology trends 2024"
  },
  {
    id: 23,
    name: "Superapps",
    phase: "Plateau of Productivity",
    x: 75,
    y: 55,
    trl: 9,
    impact: 8,
    strategicFit: 7,
    barriers: 5,
    sustainability: 3,
    category: "Experience Tech",
    notes: "WeChat model proven in Asia. Western attempts (Twitter/X) struggling but concept validated in specific markets and contexts.",
    source: "Digital platform analysis 2024"
  },
  {
    id: 24,
    name: "Machine Customers",
    phase: "Innovation Trigger",
    x: 10,
    y: 70,
    trl: 4,
    impact: 9,
    strategicFit: 8,
    barriers: 8,
    sustainability: 3,
    category: "AI & Automation",
    notes: "AI agents making autonomous purchasing decisions. Early examples in B2B procurement and smart home replenishment.",
    source: "Gartner emerging tech 2024"
  },
  {
    id: 25,
    name: "AI-Driven Cyber Defense",
    phase: "Slope of Enlightenment",
    x: 55,
    y: 50,
    trl: 8,
    impact: 9,
    strategicFit: 9,
    barriers: 6,
    sustainability: 2,
    category: "Trust & Security",
    notes: "AI for threat detection maturing rapidly. Autonomous response systems emerging but human oversight still critical.",
    source: "Cybersecurity industry reports 2024"
  },
  {
    id: 26,
    name: "Quantum-Safe Networking",
    phase: "Innovation Trigger",
    x: 14,
    y: 50,
    trl: 5,
    impact: 9,
    strategicFit: 8,
    barriers: 8,
    sustainability: 1,
    category: "Quantum Tech",
    notes: "Network infrastructure implementing PQC and quantum key distribution. Standards emerging but deployment complexity high.",
    source: "Network security research 2024"
  },
  {
    id: 27,
    name: "Decentralized Digital Identity (DID)",
    phase: "Trough of Disillusionment",
    x: 48,
    y: 30,
    trl: 6,
    impact: 8,
    strategicFit: 7,
    barriers: 8,
    sustainability: 1,
    category: "Trust & Security",
    notes: "W3C standards exist but adoption slow. User experience and governance challenges. Some government pilots showing promise.",
    source: "Digital identity standards 2024"
  },
  {
    id: 28,
    name: "Green IT & Sustainable Data Centers",
    phase: "Slope of Enlightenment",
    x: 68,
    y: 57,
    trl: 8,
    impact: 8,
    strategicFit: 8,
    barriers: 6,
    sustainability: 1,
    category: "Sustainability",
    notes: "Liquid cooling, renewable energy, and waste heat recovery becoming standard. AI workloads driving new efficiency imperatives.",
    source: "Data center industry reports 2024"
  },
  {
    id: 29,
    name: "Circular Electronics Manufacturing",
    phase: "Slope of Enlightenment",
    x: 63,
    y: 56,
    trl: 7,
    impact: 8,
    strategicFit: 6,
    barriers: 7,
    sustainability: 1,
    category: "Sustainability",
    notes: "Design for disassembly and materials recovery gaining traction. EU regulations accelerating adoption. Economics improving.",
    source: "Circular economy research 2024"
  },
  {
    id: 30,
    name: "AI for Climate Resilience",
    phase: "Innovation Trigger",
    x: 12,
    y: 75,
    trl: 5,
    impact: 9,
    strategicFit: 9,
    barriers: 7,
    sustainability: 1,
    category: "Climate Tech",
    notes: "AI models for climate prediction, adaptation planning, and resource optimization. Early deployments in agriculture and urban planning.",
    source: "Climate technology analysis 2024"
  }
];

// ChatGPT Generated Dataset
const technologiesGPT = [
  // 🧠 AI & Automation
  {
    id: 1,
    name: "Agentic AI",
    phase: "peak",
    x: 30,
    y: 14,
    trl: 5,
    impact: 10,
    barriers: 7,
    sustainability: 5,
    strategicFit: 10,
    category: "AI & Automation",
    notes:
      "Autonomous AI systems capable of task orchestration and decision-making. Foundational for smart mobility and robotics applications.",
    source: "Gartner 2024, McKinsey 2025",
  },
  {
    id: 2,
    name: "Generative AI & Multimodal Models",
    phase: "slope",
    x: 55,
    y: 70,
    trl: 8,
    impact: 9,
    barriers: 3,
    sustainability: 4,
    strategicFit: 9,
    category: "AI & Automation",
    notes:
      "Mature generative models combining text, vision, and audio for city planning, robotics, and analytics.",
    source: "Gartner 2024, CB Insights 2025",
  },
  {
    id: 3,
    name: "AI-Augmented Software Engineering",
    phase: "slope",
    x: 58,
    y: 65,
    trl: 8,
    impact: 8,
    barriers: 3,
    sustainability: 4,
    strategicFit: 9,
    category: "Developer Tools",
    notes:
      "AI copilots and code generation improving R&D and digital twin development productivity.",
    source: "Gartner 2024",
  },
  {
    id: 4,
    name: "AI Safety & Governance Platforms",
    phase: "slope",
    x: 50,
    y: 60,
    trl: 7,
    impact: 8,
    barriers: 5,
    sustainability: 3,
    strategicFit: 10,
    category: "Trust & Security",
    notes:
      "Responsible AI, risk management, and compliance tooling supporting ethical smart city operations.",
    source: "WEF 2025, McKinsey 2025",
  },
  {
    id: 5,
    name: "Multi-Agent Systems",
    phase: "innovation",
    x: 10,
    y: 80,
    trl: 4,
    impact: 9,
    barriers: 7,
    sustainability: 5,
    strategicFit: 10,
    category: "AI & Automation",
    notes:
      "Networks of cooperative AI agents enabling distributed decision-making in mobility and robotics.",
    source: "Gartner 2025",
  },

  // 🤖 Robotics & Physical AI
  {
    id: 6,
    name: "Humanoid Robots",
    phase: "peak",
    x: 35,
    y: 14,
    trl: 6,
    impact: 9,
    barriers: 8,
    sustainability: 6,
    strategicFit: 10,
    category: "Robotics",
    notes:
      "Human-like robots transforming logistics, healthcare, and service industries in future smart cities.",
    source: "Gartner 2024",
  },
  {
    id: 7,
    name: "Swarm Robotics",
    phase: "innovation",
    x: 10,
    y: 70,
    trl: 4,
    impact: 9,
    barriers: 7,
    sustainability: 5,
    strategicFit: 10,
    category: "Robotics",
    notes:
      "Cooperative robotic systems for autonomous maintenance, agriculture, and public safety operations.",
    source: "McKinsey 2025",
  },

  // ⚙️ Computing & Infrastructure
  {
    id: 8,
    name: "Edge AI & Federated Learning",
    phase: "slope",
    x: 55,
    y: 60,
    trl: 8,
    impact: 9,
    barriers: 3,
    sustainability: 3,
    strategicFit: 10,
    category: "Computing",
    notes:
      "Decentralized AI enabling low-latency analytics in mobility and IoT ecosystems.",
    source: "Gartner 2025, CB Insights 2025",
  },
  {
    id: 9,
    name: "Quantum Computing",
    phase: "innovation",
    x: 15,
    y: 50,
    trl: 3,
    impact: 10,
    barriers: 9,
    sustainability: 5,
    strategicFit: 8,
    category: "Quantum Tech",
    notes:
      "Hybrid quantum-classical computation enabling advanced optimization for smart infrastructure.",
    source: "McKinsey 2025",
  },
  {
    id: 10,
    name: "Post-Quantum Cryptography",
    phase: "slope",
    x: 66,
    y: 55,
    trl: 6,
    impact: 9,
    barriers: 5,
    sustainability: 4,
    strategicFit: 9,
    category: "Trust & Security",
    notes: "Quantum-resilient cryptography securing mobility and IoT networks.",
    source: "WEF 2025",
  },

  // 🌍 Energy & Climate Tech
  {
    id: 11,
    name: "Structural Battery Composites",
    phase: "slope",
    x: 52,
    y: 58,
    trl: 7,
    impact: 9,
    barriers: 6,
    sustainability: 3,
    strategicFit: 8,
    category: "Energy & Materials",
    notes: "Lightweight power-storing materials for drones, robotics, and EVs.",
    source: "WEF 2025",
  },
  {
    id: 12,
    name: "Green Nitrogen Fixation",
    phase: "slope",
    x: 55,
    y: 55,
    trl: 6,
    impact: 8,
    barriers: 5,
    sustainability: 2,
    strategicFit: 9,
    category: "Climate Tech",
    notes:
      "Eco-friendly ammonia synthesis supporting sustainable urban agriculture.",
    source: "WEF 2025",
  },
  {
    id: 13,
    name: "Next-Gen Nuclear (SMRs)",
    phase: "slope",
    x: 50,
    y: 60,
    trl: 7,
    impact: 9,
    barriers: 7,
    sustainability: 3,
    strategicFit: 8,
    category: "Energy & Materials",
    notes:
      "Small modular reactors providing decentralized, safe energy for smart city grids.",
    source: "WEF 2025",
  },
  {
    id: 14,
    name: "Carbon Capture & Utilization",
    phase: "slope",
    x: 48,
    y: 40,
    trl: 8,
    impact: 9,
    barriers: 5,
    sustainability: 2,
    strategicFit: 9,
    category: "Climate Tech",
    notes:
      "Industrial carbon reduction technology enabling sustainability-driven urban innovation.",
    source: "McKinsey 2025",
  },

  // 🧬 BioTech & Health
  {
    id: 15,
    name: "Engineered Living Therapeutics",
    phase: "slope",
    x: 52,
    y: 63,
    trl: 6,
    impact: 9,
    barriers: 7,
    sustainability: 5,
    strategicFit: 7,
    category: "Healthcare",
    notes:
      "Engineered microbial therapies reshaping precision medicine and environmental bioremediation.",
    source: "WEF 2025",
  },
  {
    id: 16,
    name: "RNA & Epigenetic Therapies",
    phase: "slope",
    x: 58,
    y: 65,
    trl: 7,
    impact: 9,
    barriers: 6,
    sustainability: 5,
    strategicFit: 7,
    category: "Healthcare",
    notes:
      "Next-generation RNA therapeutics with potential cross-domain bio-digital applications.",
    source: "CB Insights 2025",
  },
  {
    id: 17,
    name: "Bio-Digital Interfaces",
    phase: "innovation",
    x: 15,
    y: 60,
    trl: 4,
    impact: 10,
    barriers: 8,
    sustainability: 5,
    strategicFit: 10,
    category: "BioTech",
    notes:
      "Brain-computer and neural interface systems connecting cognition with robotics and smart devices.",
    source: "McKinsey 2025",
  },
  {
    id: 18,
    name: "Synthetic Biology Platforms",
    phase: "slope",
    x: 50,
    y: 45,
    trl: 7,
    impact: 8,
    barriers: 5,
    sustainability: 4,
    strategicFit: 8,
    category: "Healthcare",
    notes:
      "Programmable biological systems enabling materials and healthcare innovation.",
    source: "WEF 2025",
  },

  // 🌐 Infrastructure & Connectivity
  {
    id: 19,
    name: "6G Networks",
    phase: "innovation",
    x: 12,
    y: 65,
    trl: 4,
    impact: 9,
    barriers: 8,
    sustainability: 5,
    strategicFit: 9,
    category: "Connectivity",
    notes:
      "Ultra-low latency wireless foundation for robotics and IoT ecosystems.",
    source: "Gartner 2024",
  },
  {
    id: 20,
    name: "Satellite Internet Constellations",
    phase: "plateau",
    x: 80,
    y: 50,
    trl: 8,
    impact: 8,
    barriers: 4,
    sustainability: 4,
    strategicFit: 8,
    category: "Space Tech",
    notes:
      "Low Earth orbit satellite networks delivering global IoT connectivity.",
    source: "CB Insights 2025",
  },
  {
    id: 21,
    name: "Collaborative Sensing Networks",
    phase: "slope",
    x: 58,
    y: 68,
    trl: 7,
    impact: 9,
    barriers: 4,
    sustainability: 3,
    strategicFit: 10,
    category: "IoT & Sensors",
    notes:
      "AI-enhanced sensor fusion supporting adaptive infrastructure and smart mobility systems.",
    source: "WEF 2025",
  },

  // 💼 Enterprise & Experience Tech
  {
    id: 22,
    name: "Digital Twin of the Customer",
    phase: "trough",
    x: 40,
    y: 20,
    trl: 6,
    impact: 8,
    barriers: 6,
    sustainability: 5,
    strategicFit: 8,
    category: "Experience Tech",
    notes:
      "Personalized digital avatars integrating behavioral and transaction data for urban analytics.",
    source: "Gartner 2024",
  },
  {
    id: 23,
    name: "Superapps",
    phase: "slope",
    x: 70,
    y: 55,
    trl: 9,
    impact: 8,
    barriers: 3,
    sustainability: 4,
    strategicFit: 8,
    category: "Experience Tech",
    notes:
      "Unified ecosystems combining commerce, mobility, and city services.",
    source: "Gartner 2024",
  },
  {
    id: 24,
    name: "Machine Customers",
    phase: "innovation",
    x: 10,
    y: 75,
    trl: 4,
    impact: 9,
    barriers: 7,
    sustainability: 5,
    strategicFit: 9,
    category: "AI & Automation",
    notes:
      "Autonomous digital entities performing B2B and B2C transactions in connected ecosystems.",
    source: "Gartner 2025",
  },
  {
    id: 25,
    name: "AI-Driven Cyber Defense",
    phase: "slope",
    x: 55,
    y: 65,
    trl: 8,
    impact: 9,
    barriers: 4,
    sustainability: 3,
    strategicFit: 10,
    category: "Trust & Security",
    notes:
      "Self-learning cybersecurity systems protecting AI, IoT, and robotic platforms.",
    source: "McKinsey 2025",
  },
  {
    id: 26,
    name: "Quantum-Safe Networking",
    phase: "innovation",
    x: 18,
    y: 55,
    trl: 4,
    impact: 9,
    barriers: 8,
    sustainability: 5,
    strategicFit: 9,
    category: "Quantum Tech",
    notes:
      "Quantum-secure communications protecting next-gen city and robotic systems.",
    source: "Gartner 2025",
  },
  {
    id: 27,
    name: "Decentralized Digital Identity (DID)",
    phase: "slope",
    x: 50,
    y: 63,
    trl: 7,
    impact: 9,
    barriers: 5,
    sustainability: 3,
    strategicFit: 10,
    category: "Trust & Security",
    notes:
      "Privacy-preserving identity systems foundational for secure mobility ecosystems.",
    source: "WEF 2025",
  },

  // 🌱 Sustainability & Green IT
  {
    id: 28,
    name: "Green IT & Sustainable Data Centers",
    phase: "slope",
    x: 60,
    y: 60,
    trl: 9,
    impact: 8,
    barriers: 3,
    sustainability: 2,
    strategicFit: 9,
    category: "Sustainability",
    notes:
      "Energy-optimized infrastructure minimizing data center carbon footprint.",
    source: "CB Insights 2025",
  },
  {
    id: 29,
    name: "Circular Electronics Manufacturing",
    phase: "innovation",
    x: 20,
    y: 58,
    trl: 5,
    impact: 8,
    barriers: 5,
    sustainability: 2,
    strategicFit: 9,
    category: "Sustainability",
    notes:
      "Circular production models reducing e-waste across smart city ecosystems.",
    source: "WEF 2025",
  },
  {
    id: 30,
    name: "AI for Climate Resilience",
    phase: "slope",
    x: 50,
    y: 62,
    trl: 8,
    impact: 10,
    barriers: 4,
    sustainability: 2,
    strategicFit: 10,
    category: "Climate Tech",
    notes:
      "AI-driven modeling for predicting and mitigating climate impacts on cities and mobility.",
    source: "McKinsey 2025",
  },
];

// Google Gemini Generated Dataset
// src/data/initialTechnologies.js

const technologiesGemini = [
  {
    id: 1,
    name: "Agentic AI",
    phase: "peak",
    x: 28,
    y: 12,
    trl: 4,
    impact: 10,
    barriers: 8,
    sustainability: 9,
    category: "AI & Automation",
    notes: "Autonomous AI systems capable of complex decision-making and action planning.",
    source: "Gartner Hype Cycle 2025",
    strategicFit: 10,
  },
  {
    id: 2,
    name: "Generative AI & Multimodal Models",
    phase: "trough",
    x: 44,
    y: 22,
    trl: 7,
    impact: 9,
    barriers: 5,
    sustainability: 6,
    category: "AI & Automation",
    notes: "AI capable of creating text, images, code, and 3D models from various inputs.",
    source: "Industry Consensus 2025",
    strategicFit: 7,
  },
  {
    id: 3,
    name: "AI-Augmented Software Engineering",
    phase: "slope",
    x: 62,
    y: 48,
    trl: 7,
    impact: 8,
    barriers: 4,
    sustainability: 5,
    category: "Developer Tools",
    notes: "AI copilots and autonomous agents automating code generation, testing, and deployment.",
    source: "Industry Consensus 2025",
    strategicFit: 8,
  },
  {
    id: 4,
    name: "AI Safety & Governance Platforms",
    phase: "slope",
    x: 55,
    y: 52,
    trl: 6,
    impact: 9,
    barriers: 6,
    sustainability: 3,
    category: "Trust & Security",
    notes: "Tools to monitor, secure, and ensure ethical, reliable, and compliant operation of AI systems.",
    source: "Gartner 2025",
    strategicFit: 9,
  },
  {
    id: 5,
    name: "Multi-Agent Systems",
    phase: "peak",
    x: 24,
    y: 10,
    trl: 4,
    impact: 8,
    barriers: 7,
    sustainability: 8,
    category: "AI & Automation",
    notes: "The coordination of multiple specialized agents to achieve complex goals beyond any single agent's capability.",
    source: "Gartner Hype Cycle 2025",
    strategicFit: 10,
  },
  {
    id: 6,
    name: "Humanoid Robots",
    phase: "peak",
    x: 33,
    y: 14,
    trl: 4,
    impact: 10,
    barriers: 8,
    sustainability: 5,
    category: "Robotics",
    notes: "General-purpose robots with human-like physical forms for tasks in complex, human-designed environments.",
    source: "McKinsey Tech Trends 2025",
    strategicFit: 10,
  },
  {
    id: 7,
    name: "Swarm Robotics",
    phase: "innovation",
    x: 11,
    y: 65,
    trl: 3,
    impact: 9,
    barriers: 9,
    sustainability: 6,
    category: "Robotics",
    notes: "Large groups of simple, coordinated robots for parallel tasks like large-area inspection or construction.",
    source: "Industry Research",
    strategicFit: 10,
  },
  {
    id: 8,
    name: "Edge AI & Federated Learning",
    phase: "slope",
    x: 68,
    y: 45,
    trl: 7,
    impact: 8,
    barriers: 4,
    sustainability: 3,
    category: "Computing",
    notes: "Processing data locally (Edge AI) and collaborative model training on distributed data (Federated Learning).",
    source: "Gartner 2025",
    strategicFit: 9,
  },
  {
    id: 9,
    name: "Quantum Computing",
    phase: "innovation",
    x: 8,
    y: 88,
    trl: 3,
    impact: 10,
    barriers: 9,
    sustainability: 8,
    category: "Quantum Tech",
    notes: "Utilizing quantum mechanics to solve problems intractable for classical computers (e.g., optimization, simulation).",
    source: "McKinsey/Bain 2025",
    strategicFit: 8,
  },
  {
    id: 10,
    name: "Post-Quantum Cryptography",
    phase: "innovation",
    x: 9,
    y: 75,
    trl: 4,
    impact: 10,
    barriers: 6,
    sustainability: 2,
    category: "Trust & Security",
    notes: "New cryptographic algorithms designed to resist attacks from future quantum computers.",
    source: "NIST/Industry",
    strategicFit: 9,
  },
  {
    id: 11,
    name: "Structural Battery Composites",
    phase: "innovation",
    x: 11,
    y: 70,
    trl: 4,
    impact: 8,
    barriers: 7,
    sustainability: 3,
    category: "Energy & Materials",
    notes: "Materials that simultaneously store energy and bear mechanical load, reducing weight/space.",
    source: "Nature/Industry Research",
    strategicFit: 8,
  },
  {
    id: 12,
    name: "Green Nitrogen Fixation",
    phase: "innovation",
    x: 6,
    y: 94,
    trl: 2,
    impact: 7,
    barriers: 9,
    sustainability: 1,
    category: "Climate Tech",
    notes: "Developing highly energy-efficient and low-carbon methods for producing ammonia (fertilizer).",
    source: "Bio-Tech Research",
    strategicFit: 4,
  },
  {
    id: 13,
    name: "Next-Gen Nuclear (SMRs)",
    phase: "slope",
    x: 58,
    y: 55,
    trl: 6,
    impact: 9,
    barriers: 7,
    sustainability: 2,
    category: "Energy & Materials",
    notes: "Small Modular Reactors (SMRs) offering scalable, safer, and faster-to-deploy low-carbon energy.",
    source: "World Nuclear Assoc.",
    strategicFit: 7,
  },
  {
    id: 14,
    name: "Carbon Capture & Utilization",
    phase: "slope",
    x: 65,
    y: 50,
    trl: 7,
    impact: 8,
    barriers: 6,
    sustainability: 8,
    category: "Climate Tech",
    notes: "Technologies that capture CO2 from industrial sources or the air and convert it into useful products or materials.",
    source: "IEA/Industry",
    strategicFit: 8,
  },
  {
    id: 15,
    name: "Engineered Living Therapeutics",
    phase: "innovation",
    x: 8,
    y: 80,
    trl: 3,
    impact: 8,
    barriers: 9,
    sustainability: 5,
    category: "Healthcare",
    notes: "Cells or organisms modified to sense and respond to disease in the body.",
    source: "Bio-Tech Research",
    strategicFit: 2,
  },
  {
    id: 16,
    name: "RNA & Epigenetic Therapies",
    phase: "slope",
    x: 60,
    y: 54,
    trl: 7,
    impact: 9,
    barriers: 5,
    sustainability: 4,
    category: "Healthcare",
    notes: "Treatments that control gene expression without altering the underlying DNA sequence.",
    source: "Bio-Tech Research",
    strategicFit: 2,
  },
  {
    id: 17,
    name: "Bio-Digital Interfaces",
    phase: "peak",
    x: 30,
    y: 14,
    trl: 5,
    impact: 9,
    barriers: 8,
    sustainability: 5,
    category: "BioTech",
    notes: "Technologies like Neuralink that directly connect biological systems to digital networks.",
    source: "Industry Research",
    strategicFit: 9,
  },
  {
    id: 18,
    name: "Synthetic Biology Platforms",
    phase: "slope",
    x: 56,
    y: 56,
    trl: 6,
    impact: 7,
    barriers: 6,
    sustainability: 4,
    category: "Healthcare",
    notes: "Tools and systems to engineer biological components and systems for new functions (e.g., materials, computation).",
    source: "Industry Consensus 2025",
    strategicFit: 3,
  },
  {
    id: 19,
    name: "6G Networks",
    phase: "innovation",
    x: 6,
    y: 90,
    trl: 2,
    impact: 10,
    barriers: 9,
    sustainability: 6,
    category: "Connectivity",
    notes: "Next-gen wireless offering terahertz speeds, AI integration, and extreme low latency/massive density.",
    source: "ITU-R Research",
    strategicFit: 10,
  },
  {
    id: 20,
    name: "Satellite Internet Constellations",
    phase: "slope",
    x: 70,
    y: 46,
    trl: 8,
    impact: 8,
    barriers: 5,
    sustainability: 7,
    category: "Space Tech",
    notes: "Massive LEO/MEO satellite networks (Starlink, OneWeb) providing global, low-latency, high-speed internet access.",
    source: "Industry Consensus 2025",
    strategicFit: 8,
  },
  {
    id: 21,
    name: "Collaborative Sensing Networks",
    phase: "plateau",
    x: 82,
    y: 48,
    trl: 8,
    impact: 8,
    barriers: 4,
    sustainability: 3,
    category: "IoT & Sensors",
    notes: "A network where individual sensors (cameras, environmental, LiDAR) share and fuse data to create a single, real-time picture of the environment.",
    source: "Industry Consensus 2025",
    strategicFit: 10,
  },
  {
    id: 22,
    name: "Digital Twin of the Customer",
    phase: "trough",
    x: 46,
    y: 28,
    trl: 5,
    impact: 6,
    barriers: 7,
    sustainability: 6,
    category: "Experience Tech",
    notes: "A dynamic, virtual model of an individual citizen or demographic, used for personalized services and planning.",
    source: "Gartner Hype Cycle CX 2024",
    strategicFit: 6,
  },
  {
    id: 23,
    name: "Superapps",
    phase: "slope",
    x: 72,
    y: 50,
    trl: 7,
    impact: 7,
    barriers: 5,
    sustainability: 7,
    category: "Experience Tech",
    notes: "All-in-one digital platforms offering a range of consolidated services (e.g., payments, transport, government services).",
    source: "Industry Consensus 2025",
    strategicFit: 6,
  },
  {
    id: 24,
    name: "Machine Customers",
    phase: "peak",
    x: 26,
    y: 14,
    trl: 4,
    impact: 7,
    barriers: 8,
    sustainability: 7,
    category: "AI & Automation",
    notes: "Non-human entities (AI agents, devices, robots) that autonomously negotiate and purchase goods or services.",
    source: "Gartner 2025",
    strategicFit: 5,
  },
  {
    id: 25,
    name: "AI-Driven Cyber Defense",
    phase: "plateau",
    x: 85,
    y: 50,
    trl: 9,
    impact: 9,
    barriers: 3,
    sustainability: 3,
    category: "Trust & Security",
    notes: "Autonomous systems using AI/ML to detect, analyze, and automatically respond to cyber threats in real-time.",
    source: "Industry Consensus 2025",
    strategicFit: 9,
  },
  {
    id: 26,
    name: "Quantum-Safe Networking",
    phase: "slope",
    x: 64,
    y: 51,
    trl: 6,
    impact: 9,
    barriers: 7,
    sustainability: 3,
    category: "Quantum Tech",
    notes: "Implementing quantum key distribution (QKD) or PQC algorithms across network infrastructure.",
    source: "Industry Research",
    strategicFit: 9,
  },
  {
    id: 27,
    name: "Decentralized Digital Identity (DID)",
    phase: "slope",
    x: 66,
    y: 49,
    trl: 7,
    impact: 8,
    barriers: 6,
    sustainability: 4,
    category: "Trust & Security",
    notes: "User-controlled, privacy-preserving digital identifiers, often underpinned by blockchain/DLT.",
    source: "Gataca Trends 2025",
    strategicFit: 7,
  },
  {
    id: 28,
    name: "Green IT & Sustainable Data Centers",
    phase: "plateau",
    x: 88,
    y: 52,
    trl: 9,
    impact: 9,
    barriers: 3,
    sustainability: 1,
    category: "Sustainability",
    notes: "Focus on energy efficiency, optimized cooling, and renewable power for all data and computing infrastructure.",
    source: "Industry Consensus 2025",
    strategicFit: 9,
  },
  {
    id: 29,
    name: "Circular Electronics Manufacturing",
    phase: "slope",
    x: 52,
    y: 58,
    trl: 6,
    impact: 7,
    barriers: 7,
    sustainability: 2,
    category: "Sustainability",
    notes: "Designing electronics for repair, refurbishment, and full material recovery/recycling to reduce waste.",
    source: "WEEE Forum/Industry",
    strategicFit: 6,
  },
  {
    id: 30,
    name: "AI for Climate Resilience",
    phase: "peak",
    x: 36,
    y: 15,
    trl: 5,
    impact: 9,
    barriers: 6,
    sustainability: 3,
    category: "Climate Tech",
    notes: "Using AI/ML to model, predict, and automate responses to climate risks (e.g., extreme heat, floods) within urban areas.",
    source: "UN/Industry Research",
    strategicFit: 9,
  },
];


// DeepSeek Generated Dataset 
const technologiesDeepSeek = [
  { id: 1, name: "Agentic AI", phase: "innovation", x: 8, y: 88, trl: 4, impact: 9.2, barriers: 8.5, sustainability: 6.5, strategicFit: 9.5, category: "AI & Automation", notes: "Autonomous AI systems that can plan and execute complex tasks with minimal human oversight", source: "Gartner 2024, McKinsey 2025" },
  { id: 2, name: "Generative AI & Multimodal Models", phase: "peak", x: 35, y: 14, trl: 7, impact: 9.8, barriers: 7.2, sustainability: 7.0, strategicFit: 9.0, category: "AI & Automation", notes: "Advanced AI models capable of processing and generating text, images, audio, and video simultaneously", source: "Gartner 2024, McKinsey 2024" },
  { id: 3, name: "AI-Augmented Software Engineering", phase: "enlightenment", x: 65, y: 45, trl: 7, impact: 8.7, barriers: 5.8, sustainability: 2.5, strategicFit: 8.5, category: "Developer Tools", notes: "AI tools that assist in code generation, testing, debugging, and software architecture design", source: "Gartner 2024" },
  { id: 4, name: "AI Safety & Governance Platforms", phase: "innovation", x: 10, y: 78, trl: 5, impact: 8.5, barriers: 8.0, sustainability: 3.0, strategicFit: 8.0, category: "Trust & Security", notes: "Systems for ensuring AI alignment, transparency, and ethical deployment across organizations", source: "WEF 2024, Gartner 2024" },
  { id: 5, name: "Multi-Agent Systems", phase: "innovation", x: 10, y: 68, trl: 4, impact: 8.8, barriers: 8.2, sustainability: 5.5, strategicFit: 8.8, category: "AI & Automation", notes: "Coordinated AI agents that collaborate to solve complex problems beyond individual agent capabilities", source: "McKinsey 2024" },
  { id: 6, name: "Humanoid Robots", phase: "peak", x: 35, y: 14, trl: 5, impact: 8.9, barriers: 9.0, sustainability: 4.5, strategicFit: 8.2, category: "Robotics", notes: "Bipedal robots designed for human environments with advanced manipulation and mobility", source: "CB Insights 2024" },
  { id: 7, name: "Swarm Robotics", phase: "trough", x: 45, y: 28, trl: 6, impact: 8.4, barriers: 7.8, sustainability: 3.2, strategicFit: 8.6, category: "Robotics", notes: "Coordinated groups of simple robots working together for complex tasks like search and rescue", source: "WEF 2024" },
  { id: 8, name: "Edge AI & Federated Learning", phase: "enlightenment", x: 68, y: 48, trl: 7, impact: 8.6, barriers: 6.5, sustainability: 3.8, strategicFit: 9.1, category: "Computing", notes: "AI processing on local devices with privacy-preserving distributed model training", source: "Gartner 2024, McKinsey 2024" },
  { id: 9, name: "Quantum Computing", phase: "innovation", x: 11, y: 72, trl: 3, impact: 9.5, barriers: 9.5, sustainability: 4.0, strategicFit: 7.5, category: "Quantum Tech", notes: "Quantum processors solving problems intractable for classical computers in optimization and simulation", source: "McKinsey 2024, WEF 2024" },
  { id: 10, name: "Post-Quantum Cryptography", phase: "innovation", x: 12, y: 65, trl: 5, impact: 8.3, barriers: 7.5, sustainability: 2.0, strategicFit: 8.3, category: "Trust & Security", notes: "Cryptographic algorithms resistant to attacks from both classical and quantum computers", source: "NIST 2024, Gartner 2024" },
  { id: 11, name: "Structural Battery Composites", phase: "innovation", x: 20, y: 62, trl: 4, impact: 8.0, barriers: 8.8, sustainability: 2.2, strategicFit: 7.8, category: "Energy & Materials", notes: "Battery materials that serve as both energy storage and structural components", source: "WEF 2024" },
  { id: 12, name: "Green Nitrogen Fixation", phase: "innovation", x: 16, y: 58, trl: 3, impact: 7.8, barriers: 8.5, sustainability: 1.8, strategicFit: 6.5, category: "Climate Tech", notes: "Low-energy processes for fertilizer production reducing agricultural carbon footprint", source: "Nature 2024" },
  { id: 13, name: "Next-Gen Nuclear (SMRs)", phase: "enlightenment", x: 62, y: 42, trl: 6, impact: 8.7, barriers: 8.9, sustainability: 3.5, strategicFit: 7.2, category: "Energy & Materials", notes: "Small Modular Reactors offering scalable, safer nuclear energy with reduced waste", source: "IAEA 2024, McKinsey 2024" },
  { id: 14, name: "Carbon Capture & Utilization", phase: "innovation", x: 12, y: 55, trl: 5, impact: 8.2, barriers: 8.2, sustainability: 1.5, strategicFit: 7.0, category: "Climate Tech", notes: "Technologies that capture CO2 and convert it into valuable products and materials", source: "IPCC 2024, WEF 2024" },
  { id: 15, name: "Engineered Living Therapeutics", phase: "innovation", x: 14, y: 52, trl: 3, impact: 8.9, barriers: 9.2, sustainability: 4.2, strategicFit: 6.0, category: "Healthcare", notes: "Genetically engineered cells and microbes designed as precision medical treatments", source: "Nature Biotech 2024" },
  { id: 16, name: "RNA & Epigenetic Therapies", phase: "enlightenment", x: 58, y: 50, trl: 6, impact: 8.8, barriers: 7.8, sustainability: 3.0, strategicFit: 5.8, category: "Healthcare", notes: "Next-generation genetic medicines targeting RNA and epigenetic modifications", source: "FDA 2024, McKinsey 2024" },
  { id: 17, name: "Bio-Digital Interfaces", phase: "innovation", x: 22, y: 48, trl: 4, impact: 8.5, barriers: 8.7, sustainability: 5.8, strategicFit: 7.5, category: "BioTech", notes: "Direct interfaces between biological systems and digital computing platforms", source: "WEF 2024" },
  { id: 18, name: "Synthetic Biology Platforms", phase: "enlightenment", x: 48, y: 40, trl: 6, impact: 8.6, barriers: 8.0, sustainability: 3.3, strategicFit: 6.8, category: "Healthcare", notes: "Automated platforms for designing and engineering biological systems at scale", source: "SynBio Beta 2024" },
  { id: 19, name: "6G Networks", phase: "innovation", x: 18, y: 42, trl: 2, impact: 9.0, barriers: 8.5, sustainability: 4.5, strategicFit: 9.2, category: "Connectivity", notes: "Next-generation wireless networks integrating sensing, AI, and sub-THz frequencies", source: "ITU 2024, Gartner 2024" },
  { id: 20, name: "Satellite Internet Constellations", phase: "enlightenment", x: 65, y: 48, trl: 7, impact: 7.8, barriers: 7.2, sustainability: 5.2, strategicFit: 7.8, category: "Space Tech", notes: "Global broadband networks using low-earth orbit satellite mega-constellations", source: "FCC 2024, McKinsey 2024" },
  { id: 21, name: "Collaborative Sensing Networks", phase: "innovation", x: 12, y: 38, trl: 4, impact: 8.1, barriers: 7.0, sustainability: 3.8, strategicFit: 8.9, category: "IoT & Sensors", notes: "Distributed sensor networks that share data for comprehensive environmental monitoring", source: "IEEE 2024" },
  { id: 22, name: "Digital Twin of the Customer", phase: "peak", x: 40, y: 17, trl: 5, impact: 8.4, barriers: 6.8, sustainability: 2.8, strategicFit: 8.1, category: "Experience Tech", notes: "Comprehensive virtual models of customer behavior, preferences, and journeys", source: "Gartner 2024" },
  { id: 23, name: "Superapps", phase: "enlightenment", x: 72, y: 50, trl: 7, impact: 7.9, barriers: 6.2, sustainability: 3.0, strategicFit: 7.5, category: "Experience Tech", notes: "Integrated platforms combining multiple services, apps, and functionalities", source: "McKinsey 2024" },
  { id: 24, name: "Machine Customers", phase: "innovation", x: 20, y: 35, trl: 4, impact: 8.7, barriers: 7.5, sustainability: 4.0, strategicFit: 8.4, category: "AI & Automation", notes: "Autonomous systems that can identify needs, negotiate, and make purchases without human intervention", source: "Gartner 2024" },
  { id: 25, name: "AI-Driven Cyber Defense", phase: "enlightenment", x: 68, y: 54, trl: 6, impact: 8.9, barriers: 6.5, sustainability: 2.5, strategicFit: 9.0, category: "Trust & Security", notes: "Autonomous security systems that predict, detect, and respond to threats in real-time", source: "Gartner 2024, MITRE 2024" },
  { id: 26, name: "Quantum-Safe Networking", phase: "innovation", x: 16, y: 32, trl: 3, impact: 8.2, barriers: 8.0, sustainability: 2.2, strategicFit: 8.2, category: "Quantum Tech", notes: "Network infrastructure resistant to quantum computing-based attacks", source: "NIST 2024, ITU 2024" },
  { id: 27, name: "Decentralized Digital Identity (DID)", phase: "enlightenment", x: 62, y: 54, trl: 6, impact: 8.0, barriers: 7.8, sustainability: 2.8, strategicFit: 8.5, category: "Trust & Security", notes: "Self-sovereign identity systems giving users control over their personal data", source: "WEF 2024, Gartner 2024" },
  { id: 28, name: "Green IT & Sustainable Data Centers", phase: "enlightenment", x: 75, y: 50, trl: 7, impact: 7.8, barriers: 6.0, sustainability: 1.2, strategicFit: 7.8, category: "Sustainability", notes: "Energy-efficient computing infrastructure with minimal environmental impact", source: "Uptime Institute 2024" },
  { id: 29, name: "Circular Electronics Manufacturing", phase: "innovation", x: 26, y: 14, trl: 4, impact: 7.5, barriers: 7.2, sustainability: 1.5, strategicFit: 6.8, category: "Sustainability", notes: "Closed-loop production systems that eliminate waste and maximize material reuse", source: "Ellen MacArthur 2024" },
  { id: 30, name: "AI for Climate Resilience", phase: "enlightenment", x: 58, y: 55, trl: 6, impact: 8.3, barriers: 6.8, sustainability: 1.0, strategicFit: 7.2, category: "Climate Tech", notes: "AI systems predicting climate impacts and optimizing adaptation strategies", source: "UN Climate Tech 2024, McKinsey 2024" }
];


// Data source metadata
export const dataSources = {
  claude: {
    name: "Claude AI",
    description:
      "Curated from Gartner, WEF, McKinsey, and CB Insights 2024/2025 reports",
    count: technologiesClaude.length,
    focus: "Balanced coverage across all emerging tech domains",
  },
  gpt: {
    name: "ChatGPT",
    description: "Comprehensive 30-technology dataset with expanded categories",
    count: technologiesGPT.length,
    focus:
      "Quantum, Edge, Sustainability, AI Governance, and Bio-Digital Interfaces",
  },
  gemini: {
    name: "Google Gemini",
    description:
      "Industry consensus with emphasis on market maturity assessment",
    count: technologiesGemini.length,
    focus: "TRL accuracy and barrier analysis with 2025 market perspective",
  },
  deepSeek: {
    name: "Deep Seek AI",
    description:
      "Industry consensus with emphasis on market maturity assessment",
    count: technologiesDeepSeek.length,
    focus: "TRL accuracy and barrier analysis with 2025 market perspective",
  },
};

// Export all datasets
export {
  technologiesClaude,
  technologiesGPT,
  technologiesGemini,
  technologiesDeepSeek,
};

// Default export
export default technologiesClaude;
